autoptsclient-zephyr.py
autoptsclient_common.py

When the client has multiple interfaces and autopts server is running
on private address, it cannot get the correct address for client.
This patch allows a user to specify the client ip address.

common: Add a parameter to specify the client ip address

---

ptsprojects/zephyr/gap.py
ptsprojects/zephyr/gatt.py

- According to updated GATT db also values of auto-pts pre-stored attribute values has to be changed
- Generic attribute handle method is implemented to simplify maintenance

Maintenance auto-pts zephyr week 40

---

bot/config.py.sample

s/projects/BotProjects
Fixes following error while trying to use sample
config:
File “./autoptsclient_bot.py”, line 23, in <module>
From bot.config import BotProjects
ImportError: cannot import name Botprojects

bot: Fix typo in config.py.sample

---

ptscontrol.py

This patch fixes the exception caused by invalid type for response.

ptscontrol: Fix exception due to invalid type

---

ptsprojects/stack.py
ptsprojects/zephyr/l2cap.py
ptsprojects/zephyr/l2cap_wid.py
pybtp/btp.py

This updates the L2CAP layer so that it works with PTS 7.4.1.
The script based test case style has been changed to use automatic
responses based on WID and internal 'stack' state.
1/26   L2CAP   L2CAP/LE/CPU/BV-01-C    PASS            28.114
2/26   L2CAP   L2CAP/LE/CPU/BV-02-C    PASS            18.504
3/26   L2CAP   L2CAP/LE/CPU/BI-01-C    PASS            18.646
4/26   L2CAP   L2CAP/LE/CPU/BI-02-C    PASS            18.231
5/26   L2CAP   L2CAP/LE/REJ/BI-01-C    PASS            18.978
6/26   L2CAP   L2CAP/LE/REJ/BI-02-C    PASS            99.612
7/26   L2CAP   L2CAP/COS/CFC/BV-01-C   PASS            18.315
8/26   L2CAP   L2CAP/COS/CFC/BV-02-C   PASS            18.613
9/26   L2CAP   L2CAP/COS/CFC/BV-03-C   PASS            20.139
10/26   L2CAP   L2CAP/COS/CFC/BV-04-C   PASS …

zephyr: l2cap: Update L2AP to PTS 7.4.1

---

doc/btp_spec.txt

This moves BTP specification from Zephyr so that it's accessible for
all projects.

Move BTP specification from Zephyr

---

autoptsclient_common.py
ptscontrol.py
ptsprojects/testcase.py

These parameters are only useful on server side. This fixes using latest
auto-pts with PTS 7.3.0. Autopts server cannot marshall response which
is of IntPtr type.
Relevant autoptsserver.log fragment:
```
BEGIN OnImplicitSend:
project_name: GAP <type 'str'>
wid: 47 <type 'UInt16'>
test_case_name: GAP/BROB/BCST/BV-01-C <type 'str'>
description: Please enter broadcasting mode using specified TSPX_advertising_data value and start advertising. <type 'str'>
style: MMI_Style_Ok_Cancel2 0x11141
response:  <System.IntPtr object at 0x000000000000009B [7318720]> <type 'IntPtr'> 155
response_size: 2048 <type 'UInt32'>
response_is_present:  0 <type 'StrongBox[int]'>
Calling callback.on_implicit_send
Caught exception
cannot marshal <type 'IntPtr'> objects
PTS_LOGTYPE_IMPLICIT_SEND PTS ControlServer …
```

ptscontrol: Do not send response parameter on implicit send callback

---

bot/common.py
bot/config.py.sample
bot/zephyr.py

Previously you could only specify a remote from which
you could update the sources and you could only use 'master'
branch. Moreover 'reset --hard' had been used to do an update
so there was a possibility of losing some changes.
This patch introduces an improvement to the mechanism of
updating source code repositories. There is a new section
in the bot configuration that specifies what repositories are to
be updated. This functionality supports multiple repositories.
You can specify a path to the repository, absolute
or relative, a remote and a branch. You can also specify
if you want to stash non-committed changes. If the value
is False and there are changes then the repository will not be updated.

bot/common: Improve updating sources

---

bot/common.py

Turning on the untracked_files option prevent the bot from reusing the
same repo again because the bot generates the .conf file depends on the
iut_config and it doesn't delete it after the execution.
Signed-off-by: Tedd Ho-Jeong An <tedd.an@intel.com>

bot: Ignore the untracked files

---

bot/common.py

git describe --always show uniquely abbreviated commit object as fallback
when there are no annotated tags to use.
This fixes a regression introduced in:
a3768cc bot: Use git-describe for source info

bot/common: Add '--always' flag to git describe to suppress errors

---

bot/common.py

This patch enabls allowZip64 option for large files. This was set to
False by default on Python 2.7.
Signed-off-by: Tedd Ho-Jeong An <tedd.an@intel.com>

bot: Enable Zip64 option for large files

---

README.md
autoptsclient_requirements.txt
ptsprojects/zephyr/iutctl.py

This is needed to clean up any data left before board reset.
Any data left may affect the BTP commands flow.

zephyr/iutctl: Flush serial before board reset

---

autoptsclient-bluez.py
ptsprojects/bluez/_post_tc.py
ptsprojects/bluez/btestcase.py
ptsprojects/bluez/gap.py
ptsprojects/bluez/gap_wid.py
ptsprojects/bluez/iutctl.py
ptsprojects/bluez/sm.py
ptsprojects/bluez/sm_wid.py

BlueZ support had been on hold for a while and wasn't maintained for a
while. This patch updates the code for minimal support, just enough to
run the test.
Signed-off-by: Tedd Ho-Jeong An <tedd.an@intel.com>

bluez: Minimal update for bluez support

---

workspaces/autopts-zephyr-210/autopts-zephyr-210.pqw6
workspaces/autopts-zephyr-210/autopts-zephyr-210.pts

Fix a typo in the workspace files.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

zephyr: Fix typo in workspaces

---

workspaces/autopts-zephyr-22/autopts-zephyr-22.pqw6
workspaces/autopts-zephyr-22/autopts-zephyr-22.pts

Latest updates target Zephyr version 2.2.0, so we rename the workspace.
Also versions 2.2.x may be compatible with this workspace so lets
use version 2.2.

zephyr: Fix workspace version

---

workspaces/autopts-zephyr-22/autopts-zephyr-22.pqw6
workspaces/autopts-zephyr-22/autopts-zephyr-22.pts

There were some wrong ICS settings selected int .pts file
e.g. SM OOB was enabled.
This file was generated in Launch Studio by importing
autopts-zephyr-1.14.pts file and resolving consistency issues.

zephyr: Fix workspace ICS settings

---

autoptsclient_requirements.txt

missing module used in ptsprojects/mynewt/gatt.py

Fix missing Python coloredlogs module requirement

---

README.md
autoptsclient-mynewt.py
ptsprojects/mynewt/iutctl.py

Remove mention of Zephyr, redundant argument and mention of QEMU.

mynewt: Clean up IutCtl and client

---

ptsprojects/mynewt/gap.py
ptsprojects/mynewt/gatt_wid.py

- WID 69 - size value was cast to hexadecimal, corrected to decimal.
- WID 81 - added casting of hdl and val_mtp to int, val_mtp should be larger than in WID message, so 1 was added, changed value from 4 octets to 1

Multiple WID corrections

---

ptsprojects/mynewt/gatt_wid.py

Test was failing for odd values of val_mtp, because multiplied string was of length 1, and should be even. Switched to value '11' of length 2.

Mynewt: WID 81 correction

---

pybtp/btp.py

In wid 50 data was required to mach against PTS querry. Previously, that data was countinous string wich caused failed checks. Now, this data is split into characters (modified gattc_read_uuid_rsp).

btp: changed VERIFY_VALUES saving for gattc_read_uuid_rsp

---

ptsprojects/mynewt/gatt_wid.py

PTS asks for prepare write request with data length less or equal than some random value. This value can be larger than 512, which may cause problems with current configuration. Because used value can be smaller than requested, value of 1 always works.

Mynewt: gatt_wid_76 patched (GATT/CL/GAW/BV-05-C) - mtp_value

---

ptsprojects/mynewt/gap_wid.py

In test In test GAP/BOND/BON/BV-04-C sleep(2) causes inconclusive result.
Removing it fixes the issue.

Mynewt: gap_wid_77 correction

---

ptsprojects/bluez/README.md

This patch removes the section of changing capability for using BT MGMT
API.

bluez: Remove the capability setting

---

pybtp/iutctl_common.py

If the socket to btpclient is down and we try to close it, it will cause an exception. This minor patch wraps the call in try/except to ignore it.

btp: use try/except around close socket to iut

---

doc/btp_spec.txt
pybtp/btp.py
pybtp/types.py

Specifying own addr type allows to configure IUT for GAP/BROB/BCST/BV-04

btp: use own_addr_type instead of use own address

---

ptsprojects/mynewt/mesh.py

This PR updates mesh in Mynewt project of bot with changes that appeared in Zephyr's one, and apply to both. Changes contain testcase handling and PIXIT andjustments.

ptsprojects/mynewt/mesh.py: sync with zephyr

---

workspaces/Mynewt Nimble Host/Mynewt Nimble Host.pqw6

Workspace must not include changes from PR 370, as Nimble doesn't
support EATT yet, and changed ICS indicate it does, altering the way
L2CAP bearer is chosen. This causes GATT test cases to fail at
preamble stage.

Mynewt Nimble Host: EATT not yet supported

---

ptsprojects/zephyr/gap_wid.py

Tests performed with Python 3 port of auto-pts revealed inconsistency
with spec in this wid. GAP/DISC/GENM/BV-03-C is passing in current
version, but not in  port. Although it's currently not affecting tests,
wid should call btp.gap_set_nonconn(), as instructed in TS.

Zephyr: gap wid51 synced with spec

---

bot/zephyr.py

name "nrf52840_pca10056" is deprecated and "nrf52840dk_nrf52840"
should be used

Zephyr: correct deprecated board name

---

autoptsclient_common.py
ptsprojects/testcase.py

Test cases were already past the init state and the test runner would
get stuck in an infinite loop. Previously the test cases were copied
so this was not a problem.

common: Fix retry in test cases

---

README.md

this is just minor fix on documentation page to format correctly.

fix for Bluez documentation

---

pybtp/iutctl_common.py

'line' was bytes and needs to be str.

common: Fix rtt2pty usage in Python3

---

ptscontrol.py

PTS since version 8.0.0 requires the automation framework to connect to
a dongle by calling a new API. This patch introduces this change to
auto-pts framework.

ptscontrol: Update get_bluetooth_address API to PTS 8.0.0

---

ptsprojects/zephyr/gap_wid.py

It is used by GAP/DISC/GENM/BV-04-C.

wid: Fix GAP WID #52 that IUT is in Undirected Connectable Mode

---

wid/l2cap.py

They are used by L2CAP/COS/CFC/BV-01-C and L2CAP/COS/CFC/BV-02-C.

wid: Fix L2CAP WID_43 and WID_38 for PTS 8.0.0

---

wid/mmdl.py

Without the cast the sensor_value would not be an integer.

wid/mmdl: Fix Python 3 integer division

---

README.md

Solves #335 
Added Slack channel (two links: direct and indirect one) info in README.md.

README: Add Slack Channel

---

ptsprojects/mynewt/gap_wid.py
pybtp/btp.py

Wid 157 asks to check if advertising report and scan response were received by IUT. Previously,
we checked if addr type and addr fit PTS address. PTS 8.0.1 uses random address, so these values
will not be valid. Instead, we shall parse scan report and response data and check if it was
received from any of discovered devices.

Mynewt: fix GAP wid 157

---

ptsprojects/mynewt/gap_wid.py
ptsprojects/mynewt/gatt_wid.py
ptsprojects/stack.py
wid/l2cap.py

Tests that cannot be fixed for now are:
- GAP/SEC/SEM/BV-29-C - PTS errata CASE0070978 - first alternative of test ending is not working
- L2CAP/ECFC/BV-24-C - TSE 15582 - Test demands reconfiguration of MPS, which has static size in Mynewt (as it's not required to be dynamic as per Core spec)

PTS 8.0.1 Mynewt fixes

---

pybtp/btp.py

Sometimes passkey begins with one or more zeros. During unpacking,
this information is lost, as passkey in bytes packet is converted to
int. Now, passkey is converted to string and lost zeros are added.
This prevents returning invalid passkey to PTS with len <6.

btp: fix for passkeys with leading zeros

---

ptsprojects/zephyr/l2cap.py
wid/l2cap.py

This commit fixes and/or adds tests expecting Insufficient
: Authentication/Authrization/Key Size errors on L2CAP connect request

Zephyr: L2CAP/LE/CFC/BV fixes

---

ptsprojects/mynewt/l2cap.py

Added support for tests that check behavior of IUT on L2CAP
connection security errors. Tests 11, 13 and 15 require listening
on predefined PSMs, which identify security requirments of the link.

Mynewt: added support for L2CAP/LE/CFC/BV-[10-15]-C tests

---

pybtp/btp.py

gap_passkey_disp_ev_ saves passkey as string so we need to convert it
to int before comparing to int.

var_store_get_wrong_passkey: convert pk to int before comparison

---

autoptsserver.py
bot/common.py
bot/mynewt.py
bot/zephyr.py

Move old logs from logs/ into oldlogs/, so after a test run is complete, logs.zip contains only logs from last run.
Compress logs into separate .zip files instead of one large .zip, so it will be easier to download from disk logs of just a single test case.
Remove old broken temp workspaces instead of collecting them.

bot: Add logs cleanup before running tests and change logs zipping way

---

bot/common.py

and do not attach the file with unknown extension.
Occurs when no app was associated with the extension
or under Windows in Registry Editor at
Computer\HKEY_CLASSES_ROOT\<extension_name>
there are missing variables "Content Type" and "PerceivedType".

bot: Print info when mimetype exception occurs

---

autoptsclient_common.py

AttributeError: 'NoneType' object has no attribute 'startswith'
that occured when trying to run autoptsclient-zephyr.py with qemu.

common: Fix AttributeError at args parsing

---

autoptsclient_common.py

as these are valid PTS results, not caused by problems with connection
to server, like XML-RPC ERROR.
(--recovery option feature)

common: Do not run recovery steps when INCONC or FAIL

---

bot/zephyr.py

autoprojects.iutctl.init(args["kernel_image"], tty, args["board"])
TypeError: init() takes 1 positional argument but 3 were given
that occured after change in ptsproject/zephyr/iutctl.py:
def init(kernel_image, tty_file, board=None, use_rtt2pty=False))
to
def init(args)

bot: Fix TypeError

---

autoptsserver.py
ptscontrol.py

The timeout was badly compared because the time has been counted since
the last PTS restart and the PTS is not restarted on each test case.
Now the time is counted from the start of a test case.

autoptsserver: Fix superguard option

---

ptsprojects/mynewt/iutctl.py
ptsprojects/zephyr/iutctl.py
pybtp/iutctl_common.py

When stopping client should wait for socat process to terminate.
Otherwise we may end up with connection error on next start if
process scheduling is unlucky (seems to happen more often on Windows).
This also allows to get rid of sleep(2) while closing BTP socket saving
4 seconds of every test run.

Fix waiting for socat process to stop

---

README.md
autoptsclient_common.py
bot/mynewt.py
bot/zephyr.py

Add mode in which retry is always executed, even if test passes.
This allows to execute every test multiple times regardless
of the result.

Add stress test mode

---

autoptsserver.py
bot/common.py
bot/mynewt.py
bot/zephyr.py

When the gdrive option is enabled on bot, after tests, bot client
will send to autopts server the signal to upload collected Bluetooth
Protocol Viewer logs to the specified folder on the GDrive.
Add default client and server ports at parsing args.

bot: autoptsserver: Add uploading BPV logs to GDrive

---

ptsprojects/zephyr/gatt.py

We need to add two different services, so randomize UUID to avoid
duplication

Zephyr: fix GATT/SR/GAS/BV-01-C

---

tools/btpclient.py

- Reserved word as a variable name
- unnecessary eval()

tools: Fix btpclient.py

---

autoptsclient_common.py

in autoptsclient_common.py at setup_project_pixits:
mod = getattr(autoprojects, profile)
AttributeError: module 'ptsprojects.mynewt' has no attribute 'mmdl'

common: Fix AttributeError

---

autoptsclient_common.py
ptsprojects/bluez/gap.py
ptsprojects/bluez/sm.py
ptsprojects/bluez/sm_wid.py
ptsprojects/mynewt/gap.py
ptsprojects/mynewt/gatt.py
ptsprojects/mynewt/l2cap.py
ptsprojects/mynewt/mesh.py
ptsprojects/mynewt/sm.py
ptsprojects/zephyr/dis.py
ptsprojects/zephyr/gap.py
ptsprojects/zephyr/gatt.py
ptsprojects/zephyr/l2cap.py
ptsprojects/zephyr/mesh.py
ptsprojects/zephyr/sm.py
wid/dis.py
wid/gap.py
wid/gatt.py
wid/l2cap.py
wid/sm.py

When 2 or more IUTs are under test at the same time and they share the
name, PTS might choose wrong board and connect to it. Now, last 3 parts
of PTS dongle address are appended to the end of IUTs' name to
distinguish them from each other.
This affects only tests that rely on IXIT
"TSPX_iut_device_name_in_adv_packet_for_random_address", as only then
this name is actually used. This means that default device name stays
the same as "Tester" for GATT (uses static address), L2CAP and MESH
test suites.

Generate unique names for IUT

---

ptsprojects/zephyr/iutctl.py

BTP timeouts started to occur in qemu mode after replacing time.sleep(2)
in commit 0916d6c 'Fix waiting for socat process to stop' with waiting
for socat process to terminate.
This solves, at least temporarily, the issue #521.

zephyr: qemu: Workaround for issue #521

---

bot/mynewt.py
bot/zephyr.py

config.py configuration:
z['git'] = {
...
}
is now optional, for zephyr and mynewt.

bot: Make git config optional

---

ptsprojects/mynewt/gatt_wid.py

Before verifying data written by PTS we should handle
gatts_attr_value_changed_ev - calling gatts_get_attr_val first will
lead to receiving value change event when we want response to command -
op code error will occur. Receiving value change event also means
that there's actual data to be checked.

Mynewt: fix GATT/SR/GAW/BV-01-C

---

ptsprojects/mynewt/gatt.py
ptsprojects/zephyr/gatt.py

This object contains `verify values` functions that are required
for data comparison.

Init stack.gatt in preconditions for GATT tests that require it

---

bot/iut_config/zephyr.py

All ECFC test should be executed with EATT disabled.

bot: zephyr: Fix double overlay for L2CAP/ECFC/BV-11-C test

---

ptsprojects/mynewt/gatt.py

Test list contained duplicated records, test were added both by
test_cases_server and test_cases_client.

Mynewt: avoid duplicating tests in GATT list

---

wid/mesh.py

The address value should be equal to the group address.

Fix Config Model Subscription

---

wid/l2cap.py

In some tests (eg L2CAP/ECFC/BV-02-C) host is expected to autonomously
disconnect L2CAP channel on LT invalid behaviour. But PTS seems to be
asking for explicit disconnect and depending on timing BTP command may
fail if channel was already disconnected.

wid: Ignore error from L2CAP disconnect

---

ptsprojects/mynewt/mesh.py

Commit ce95c1c8e1e7924df84f765e5cc288f0fa93bef6 extended Mesh class with
auth_method attribute. Add it to Mynewt inits to avoid client crashes.

Mynewt: fix Mesh init in stack

---

ptsprojects/zephyr/mesh.py
wid/mesh.py

PTS now implements WID for enabling Node Identity so no need for this
workaround.

zephyr: Fix MESH/SR/MPXS/BV-09-C

---

ptscontrol.py

as it started with. Autoptsserver instance saves at first PTS start the address of selected dongle and on subsequent restarts passes it to PTS.

autoptsserver: After restart PTS selects the same dongle

---

doc/btp_spec.txt
wid/gap.py

We don't have separate pair and set_secutiry_level BTP commands so
just clarify expected bahviour on BTP Pair and always call it on
WID 108.

wid: Always call BTP pair on wid 108

---

bot/iut_config/zephyr.py

GAP/CONN/GCEP/BV-06-C requires privacy support enabled.

bot: zephyr: Add GAP/CONN/GCEP/BV-06-C to privacy overlay

---

autoptsclient-mynewt.py
autoptsclient_common.py
bot/common.py
bot/config.py.mynewt.sample
bot/mynewt.py
bot/zephyr.py
ptsprojects/boards/__init__.py
ptsprojects/boards/dialog_da1469x_dk_pro.py
ptsprojects/boards/nordic_pca10056.py
ptsprojects/boards/nrf52.py
ptsprojects/boards/reel_board.py
ptsprojects/mynewt/iutctl.py
ptsprojects/zephyr/iutctl.py
pybtp/iutctl_common.py

Move reset commands of boards to separate module files.
Replace nrfjprog in searching for a free device serial port and jlink serial number.
Add build and flash for dialog_da1469x-dk-pro.
Add tty_file and debugger_srn options to config of bot.

common: Make adding new boards more generic

---

bot/iut_config/zephyr.py

It is no longer needed as PTS properly increase security when required.

bot/zephyr: Remove overlay for GAP/GAT/BV-05-C

---

pybtp/btp/btp.py

bytearray(message) for message of type string fails. encoding it in utf-8 fixes this.

btp: encode string message as utf-8 in core_log_message

---

ptsprojects/zephyr/gap.py

This test require extra pairing post WID108 despite provided WID
description.

zephyr: Fix GAP/SEC/AUT/BV-21-C test

---

ptsprojects/zephyr/gap.py

This test require extra pairing post WID108 despite provided WID
description.

zephyr: Fix GAP/CONN/PRDA/BV-02-C test

---

ptsprojects/zephyr/gap.py

This is temporary workaround to make test pass until CASE0072154
is resolved. Since requesting service for triggering security is
optional we can just enabled security without it.

zephyr: Fix GAP/SEC/AUT/BV-19-C test

---

autoptsclient_common.py

I'd like to argue that there's no point in restarting PTS if a test case is not implemented by the local pts project :)
(I did disable a lot of them as PTS was hanging in some of them. Now that I got a YKUSH hub, I can also just re-enable them)

autoptsclient_common: don't restart PTS for not-implemented test cases

---

wid/gatt.py

Without this flag we will not store uuids and won't be able to verify
them in WID 17 in test GATT/CL/GAD/BV-01-C.
If the array with verify values are empty then auto-pts returns true
so it means it doesn't perform the check.

wid/gatt: WID 10 should store response to verify

---

autoptsclient_common.py

If `profiles` contains profiles not in the workspace, `get_test_case_list()` and thus `setup_test_cases()` will fail. Getting the profiles from the workspace eliminates this issue.

autoptsclient: Get profiles from workspace

---

bot/zephyr.py

Currently, when multiple boards are connected `nrfjprog` prompts the user to manually choose a board. Giving the `--snr` argument to `west flash` makes `nrfjprog` choose the correct board automatically.
Passing `tty` as the value for `--board-dir` seems to be an error. `--board-dir` should be something like `${ZEPHYR_BASE}/boards/arm/nrf52840dk_nrf52840` if one wants to override the default.

zephyr: make west flash work when multiple boards are connected

---

ptsprojects/mynewt/gatt_wid.py
pybtp/btp/gatt.py
wid/gatt.py

- Some wid functions were missing when running tests for read multiple variable length characteristics for Zephyr.
- One wid was reading multiple (not variable length) when the description asked for variable length read.

Wid functions for read multiple variable length

---

ptscontrol.py

During long PTS runs, especially with multiple dongles connected, we've seen lots of issues when auto-pts can't reconnect the dongle, after a test timeout for example. These changes fix it in majority of cases, at least.

Doing multiple attempts to connect dongle

---

bot/zephyr.py

* The nRF5340 has a flash read-back protection feature. When flash read-back protection is active, you will need to recover the chip before reflashing. If you are flashing with west, run this command for more details on the related --recover option.
* Adding recovery does not affect existing devices.
https://docs.zephyrproject.org/latest/boards/arm/nrf5340dk_nrf5340/doc/index.html#flashing

zephyr bot: add recover option for boards with app-protect

---

wid/mmdl.py

Sensor descriptor status tries to set in some dictionary
objects that do not exist. Local variables should be used instead.
Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>

mmdl: fix sensor descriptor status

---

ptsprojects/stack.py
pybtp/btp/gatt.py
wid/gatt.py

This change prevents blocking RX while waiting for a Notification Ev.
Relevant to GATT/CL/GAN and GATT/CL/GAI tests.

common: Handle GATT Notification Ev asynchronously

---

bot/common.py

Superguard timeout is given by user in minutes, so to convert them to seconds, the time is multiplied by 60. For bot, that was done twice, firstly by bot arg parser, secondly by common client arg parser.

common: Fix post parsing treatment of bot's superguard

---

ptscontrol.py

StopTestCase does not take parameters anymore. Fixes exception:
xmlrpc.client.Fault: <Fault 1: "<class 'TypeError'>:
StopTestCase() takes 1 positional argument but 3 were given">

ptscontrol: Fix StopTestCase parameter exception

---

autoptsclient_common.py

The test result was marked as progress even when there was no database
records with previous status for that test case.

common: Fix Client progress indication

---

wid/gatt.py

One test was missing from a list of exceptions.

wid: Fix GATT no long read tests

---

bot/zephyr.py

Currently while flashing, we receive a warning about the below depreciation. This pr uses the newer argument to select snr
-- west flash: using runner nrfjprog
WARNING: runners: Argument --snr is deprecated, use -i/--dev-id instead.
-- runners.nrfjprog: Recovering and erasing all flash memory.

Zephyr: bot: use -i instead of depreciated --snr

---

bot/iut_config/zephyr.py
ptsprojects/zephyr/gap.py
wid/gap.py

This includes support for required new WIDs. Also GAP tests now always
initialize GATT service as this is used in GAP tests too.

Add support for new GAP/SEC/SEM tests in PTS 8.2

---

bot/common.py

Bot was generating test list for all profiles in workspace instead of
based on config

bot: Fix test list generation

---

ptsprojects/stack.py
pybtp/btp/gap.py
wid/gap.py
wid/l2cap.py

Following tests are failing randomly due to race conditions between
former WID's event and current WID (that expects the event) timing.
The events arrives late as just couple of miliseconds in failure case.
- GAP/CONN/DCEP/BV-03-C: Connected event arrives late
- GAP/CONN/GCEP/BV-02-C:  Connected event arrives late
- GAP/SEC/AUT/BV-21-C: The bonding lost happens late
- L2CAP/COS/CFC/BV-02-C: L2CAP channel connection event arrives late
- L2CAP/COS/CFC/BV-01-C: L2CAP channel connection event arrives late
- L2CAP/LE/CFC/BV-06-C : L2CAP channel connection event arrives late

Stablize the tests failing randomly

---

autoptsclient_common.py

If the -c option was not used, no test case was run.

autoptsclient: Fix test list generation

---

bot/iut_config/zephyr.py

Those test require Secure Connections and key size validation.

bot/zephyr: Add support for more Secure Connection GAP tests

---

ptsprojects/mynewt/gap.py
ptsprojects/zephyr/gap.py
wid/gap.py

GAP WID handlers are using GATT BTP directly so stak should not
initialize GATT support, only BTP service.
This fix regression with GAP/SEC/CSIGN tests.

Fix GAP tests that use GATT server

---

ptsprojects/mynewt/iutctl.py

RTT buffer with "Logger" name has never been configured. Previously None was luckily
casted to 0, the index of the true logging buffer, which is "Terminal".
Note: Logging via RTT buffer 0 can colide with BTP communicattion via UART.
To prevent data loss, set CONSOLE_UART_FLOW_CONTROL: UART_FLOW_CTL_RTS_CTS

mynewt: Fix RTT buffer name of IUT debug logger

---

ptsprojects/zephyr/gap.py

There is no need for extra handler as GATT is always registered
for GAP tests.

zephyr: Fix GAP/SEC/AUT/BV-17-C test

---

autoptsclient_bot.py
autoptsclient_common.py
autoptsserver.py
bot/common.py
bot/mynewt.py
bot/zephyr.py
cliparser.py
ptsprojects/bluez/iutctl.py
ptsprojects/mynewt/iutctl.py
ptsprojects/zephyr/iutctl.py
utils.py

Moves the parser to separate file. Simplifies adding a new btp client support. Fixes duplicated parsing that was happening in inherited constructors of bot clients.

common: Refactor client parser

---

tools/old_overlays.py

The tool will print overlayed test cases that are not used with
the given PTS workspace.
E.g.:
$ python3 mynewt "path\to\Mynewt Nimble Host.pqw6"
Starting PTS needed to workspace parsing ...
Started new PTS daemon with pid: 7928
Old overlays:
GAP/BROB/BCST/BV-05-CGAP/CONN/ACEP/BV-03-C
GAP/PRIV/CONN/BI-01-C
GAP/PRIV/CONN/BI-10-C
GAP/BROB/BCST/BV-05-CGAP/CONN/ACEP/BV-03-C means that a comma is missing somewhere.

tools: Add old_overlays.py

---

wid/l2cap.py

**Note: This is fixing an issue that will happen on next PTS release, you can wait to merge or just merge as it is independent change with no harm.**
It looks L2CAP/LE/CID/BI-01-C will fail on next pts
release (>8.2.0). The test will be adding new step
as WID=61 to confirm IUT does not send any l2cap data.
PTS software case:
CASE0072383 (L2CAP/LE/CID/BI-01-C): Updated Test procedure
for utilizing K-frame instead of signaling packet.
I came across with the issue while testing the L2CAP.ets patch (shared in [CASE0072529](https://bluetooth.service-now.com/ess/case_detail.do?sysparm_document_key=x_bsig_case_manage_case,c95e41771b6585100999a9bfbd4bcb2e)) with all l2cap tests.

wid: Add a new wid to be ready for next pts release

---

bot/mynewt.py

check_output wrapper needed under Windows was implemented but never used.

bot: mynewt: Use check_output wrapper

---

autopts/client.py

get_available_boards takes project name, not project instance.
Before packaging commit `project` argument was holding pure name,
i.e. "zephyr", "mynewt" etc.

client: fix get_available_boards in init

---

autopts/wid/gatt_client.py

Running autopts_bot.py after the refactor gave the following error:
> Traceback (most recent call last):
File "autoptsclient_bot.py", line 31, in <module>
from autopts.bot.mynewt import main as mynewt
File "/work/tests/ble_conf/pts/auto-pts_client/autopts/bot/mynewt.py", line 28, in <module>
from autopts.ptsprojects.mynewt.iutctl import get_iut, log
File "/work/tests/ble_conf/pts/auto-pts_client/autopts/ptsprojects/mynewt/__init__.py", line 16, in <module>
import autopts.ptsprojects.mynewt.gap
File "/work/tests/ble_conf/pts/auto-pts_client/autopts/ptsprojects/mynewt/gap.py", line 23, in <module>
from autopts.ptsprojects.mynewt import gatt
File "/work/tests/ble_conf/pts/auto-pts_client/autopts/ptsprojects/mynewt/gatt.py", line 24, in <module>
from autopts.ptsprojects.mynewt.gatt_wid import …

wid/gatt_client: fix import paths after refactor

---

autopts/wid/gap.py

Connection params were updated but WID 46 handler was left unchanged.
This was affecting GAP/CONN/CPUP/BV-10-C.

wid: Fix GAP WID 46 handler

---

autopts/ptsprojects/zephyr/gap.py
autopts/ptsprojects/zephyr/gap_wid.py

Zephyr is disconnecting link on unpairing device and this was causing
races if link disconnected before PTS handled response to WID resulting
in test failures.
This patch adds custom WID handler that unpairs device on disconnect
request instead of unpair.
This was affecting GAP/SEC/CSIGN/BI-03-C

zephyr: Add support for delayed unpair

---

autopts/ptsprojects/zephyr/gatt.py

PTS seems to randomly choose characteristics for writes in that test
which results in authentication error if unlucky. Use database 6
which has only 1 long writable characteristic for consistent results.

zephyr: Make GATT/SR/GAW/BV-13-C pass consistently

---

autopts/pybtp/btp/gatt.py
autopts/wid/gatt.py

Not reading the response causes the following tests to fail:
GATT/CL/GAR/BV-08-C
GATT/CL/GAR/BI-36-C
GATT/CL/GAR/BI-38-C
GATT/CL/GAR/BI-40-C
GATT/CL/GAR/BI-44-C
Now, the response or received value to the request is read, and is available when it is checked.

gatt: Add reading response for ATT_READ_MULTIPLE_VAR_REQ

---

autopts/client.py
autopts/ptsprojects/bluez/README.md
autopts/ptsprojects/bluez/iutctl.py
cliparser.py

Fixing issues with BlueZ cli argument handling and BTPWorker initialization not being updated for BlueZ stack.
Positional argument for BlueZ btpclient conflicts with positional kernel argument. This makes BlueZ stack fail with uninitialized variable `btpclient_path`. Changed cli for btpclient path setting to an optional option `--btpclient_path`. This may no impact is imposed on other stacks, and the option is only shown in help for the relevant BlueZ stack.
Updated BlueZ iutctl according to refactored BTPWorker, that now requires a socket parameter.

Fixing issues with BlueZ cli argument handling and BTPWorker initialization

---

autopts/bot/iut_config/mynewt.py

GAP/SEC/SEM/BV-56-C and GAP/SEC/SEM/BV-57-C were moved into
legacy_m1l2.conf, remove old listings.

Nimble: remove duplicates from overlays

---

autopts/wid/gatt.py

GATT/CL/GAT/BV-03-C expects a timeout, and no response nor error code will be sent from the lower tester.
wid 141 is used in the test in PTS 8.2.2, but the bearer is not specified in the test specification.
The same logic is therefore also implemented in wid 140.
Fixes a regression caused by #748

Fix GATT/CL/GAT/BV-03-C

---

autopts/ptsprojects/zephyr/gap.py
autopts/ptsprojects/zephyr/gap_wid.py

This reverts commit 8e6c3e6aab52a8abfb75128c283684d8c927356b.
Latest PTS properly handles unpairing and disconnection and
GAP/SEC/CSIGN/BI-03-C doesn't need this workaround anymore.

Revert "zephyr: Add support for delayed unpair"

---

autopts/ptsprojects/zephyr/gatt.py

GATT/SR/GAW/BV-12-C fails occasionally, because PTS gets ATT
Insufficient Authentication/Authorization error for ATT Prepare Write.
This removes security requirements for attributes, as none of the test
cases that uses init_server_5 makes use of it.
1/3   GATT    GATT/SR/GAW/BV-10-C   PASS            48.488
2/3   GATT    GATT/SR/GAW/BV-09-C   PASS            35.655
3/3   GATT    GATT/SR/GAW/BV-12-C   PASS            44.965

zephyr: gatt: Modify GATT database for test

---

autopts/bot/iut_config/zephyr.py

This test expects that IUT notifies upper tester about authentication
error immediatelly (without first trying to increase security).

zephyr: Fix GATT/CL/GAR/BI-42-C test

---

autopts/wid/mmdl.py

We cannot guarantee that more than 1 column exist, and PTS was failing
to send us full response for other values.

mmdl: send Get Column with Raw_Value_X = 0

---

autopts/wid/l2cap.py

This WID requires IUT to start pairing.
This was affecting L2CAP/ECFC/BV-13-C and L2CAP/ECFC/BV-15-C
tests (with custom ETS from PTS issue).

Fix L2CAP WID 108 implementation

---

autopts/wid/gatt.py

GATT/CL/GAW/BI-09-C is testing Long Writes and not Reliable Write.

wid: Fix GATT WID 77 handler

---

autopts/bot/common.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py
errata/common.yaml
errata/mynewt.yaml
errata/zephyr.yaml

There is one errata/common.yaml which can be overwritten with errata/<project_name>.yaml.

bot: Split errata.yaml into multiple files

---

autopts/wid/mmdl.py

PTS does not request now specific Raw Values X's to be sent;
let's set 0x10, 0x20 if None is specified.

Fix for MMDL/CL/SNR/BV-13-C after PTS patch

---

autopts/bot/common.py
autopts/client.py

Shutdown of Bluetooth Protocol Viewer is only helpful while pulling server logs after bot run. It is annoying when analyzing test cases with simple client.

client: bot: Move pts/bpv shutdown

---

errata/common.yaml

Removed testcases that pass, either because patch was merged or PTS fixed an issue.

errata/common: cleanup Mesh tests

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

PTS 8.3.2 has new ICS which was affecting L2CAP/LE/REJ/BI-02-C test.

zephyr: Update workspace to PTS 8.3.2

---

autopts/wid/gatt.py

PTS 8.3.2 added new WID for validating read data.
This was affecting GATT/CL/GAR/BV-03-C qualification test case.

wid: Implement GATT WID 35

---

autopts/pybtp/btp/btp.py
autopts/wid/gatt.py

The GATT/CL/GAR/BV-03-C test case may randomly return very long description values, which will be truncated to ATT_MTU unless read using ATT_READ_BLOB_REQ. 
Accepting partial matches is valid as confirmed by BT SIG support and fixes these intermittent test case failures.
An example of one such long description is:
```
Please confirm IUT received Attribute Handle = '0025'O Value = '31313131313232323232333333333334343434343535353535363636363637373737373838383838393939393930303030303131313131323232323233333333333434343434353535353536363636363737373737383838383839393939393030303030313131313132323232323333333333343434343435353535353636363636373737373738383838383939393939303030303031313131313232323232333333333334343434343535353535363636363637373737373838383838393939393930303030303131313131323232 …
```

wid: Accept partial matches for GATT WID 35

---

autopts/ptsprojects/boards/nrf53.py

board: nrf53: Add CONFIG_BT_EXT_ADV=y overlay

---

autopts/ptsprojects/zephyr/gatt.py

The 2nd characteristic supporting notify was added to GATT database init_server_2 in 
https://github.com/intel/auto-pts/commit/8da4cc721f561b939cfd229770dd6136706063c0.
The above extra characteristic aims to pass GATT/SR/GAN/BV-02-C, but it still failed and further failed other TCs using init_server_2, e.g., GATT/SR/GAW/BI-38-C, GATT/SR/GAW/BV-06-C, GATT/SR/GAW/BV-11-C, etc.

zephyr: gatt: remove the 2nd notifiable characteristic from init_server2

---

README.md
autopts/bot/common.py
autopts/bot/iut_config/mynewt.py
autopts/bot/iut_config/nrf.py
autopts/bot/iut_config/zephyr.py
autopts/client.py

This commit adds configuration for bot that allows to set alternative to default setting of retries for certain tests. This allows to override default setting, which still will be valid for rest of the tests. This custom value can be smaller than default, when we know test doesn't pass and this helps us save time on retrying it, or larger, when we know test passes but not consistently, and may require more retries.

Add test specific retry count

---

autopts/client.py

When test case needs two dongles and one of them failed on prerun they stack on synchronize_instances.

Fix thread synchronisation

---

autopts/client.py

when client on windows PTS.exe won't close 
add a proxy function stop_pts（）
call it when test is end

stop pts.exe when test end

---

autopts/ptsprojects/bluez/iutctl.py
cliparser.py

Drops unused 'btp_py' flag in bluez/iutclt.py.
Fixes #852
Tested with btstack/iuctl.py which is derived from bluez/iuctl.py.

cliparser: fix btpclient_path support

---

autopts/ptsprojects/mynewt/iutctl.py
autopts/ptsprojects/zephyr/iutctl.py
cliparser.py

This shifts responsibility to the dev for performing a board reset after each test case, but avoids annoying gdb server disconnect.

zephyr, mynewt: Add --gdb option to skip board resets

---

autopts/wid/gap.py

WID 100: "Please start the Bonding Procedure in non-bondable mode:"
This WID requires non-bondable mode but PTS doesn't seem to call WID104 before that.

wid: Fix WID 100

---

autopts/ptsprojects/zephyr/gap.py

WID 112 doesn't wait for GATT reply from PTS due to PTS replying only after WID exits. This resulted in races where test randomly failed if reply for GATT read was received after next BTP command was sent resulting in command reply service ID mismatch and test abort.

zephyr: Fix race in GAP/SEC/AUT/BV-27-C handling

---

autopts/wid/gap.py

Seems like PTS expects IUT to start pairing in some tests, and doesn't in others.

wid: Fix regression in GAP/SEC/AUT/BV-19-C

---

doc/btp_aics.txt

Description is not null terminated by there is length field.

doc: Fix AICS description command definition

---

autopts/pybtp/btp/mesh.py

This command is a bit odd since while having length field it sends string including NULL termination. Unfortunatelly (at least) Zephyr implementation assumes NULL is present. So to allow for easier length validation (which isn't currently done by Zephyr) just include NULL in string length.

pybtp: Fix mesh input string command

---

autopts/ptsprojects/zephyr/aics.py
autopts/ptsprojects/zephyr/pacs.py
autopts/ptsprojects/zephyr/vcs.py
autopts/ptsprojects/zephyr/vocs.py

Every second test failed due to cached ltk.

zephyr: audio: Set pixit TSPX_delete_ltk to TRUE

---

autopts/bot/iut_config/zephyr.py

Since unicast server is enabled in bttester by default and NETCORE uses zephyrs controller, the overlays are not needed.

zephyr: Remove PACS overlays

---

autopts/ptsprojects/zephyr/mesh.py

Some tests are using GATT service to verify GATT database. Make sure it is initialized before using it.

mesh: Add missing GATT service register

---

tools/cron/common.py

The hardcoreded previous value 10h occured to be pretty annoying, because it delayed significantly every test requested with a PR comment, if in the nearest 10h happened to be scheduled any cyclical job. The issue should be handled by time estimation and prioritization of the jobs.

cron: Set minimal run time for PR job to zero

---

autopts/pybtp/btp/gap.py

Passkey was incorrectly converted from string resulting in wrong value being passed to IUT.

btp: Fix gap_passkey_entry_rsp

---

autopts/bot/iut_config/zephyr.py

Those config options are already tester defaults.

bot: Remove not needed Zephyr overlays

---

autopts/wid/gap.py

Those are used when IUT is using KeyboardDisplay IOCapa (for LE SC Passkey Comparison and legacy Passkey Entry)

wid: Add support for GAP WIDs 1003 2001 and 2004

---

autopts/bot/iut_config/zephyr.py
autopts/bot/zephyr.py

Overlays for LE Audio and MESH were moved out of prj.conf into separate files merged to Zephyr repo.

zephyr: Update overlays for LE Audio and MESH

---

autopts/wid/gap.py

In this test IUT is expected to allow access to characteristic after pairing and encryption. But test spec doesn't require authenticated pairing and PTS does Just Works pairing. To make sure PTS can always read characteristic after pairing select one that requires encryption only.

wid: Fix GAP/SEC/AUT/BV-11-C test

---

autopts/ptsprojects/zephyr/l2cap.py

This test requires sending connection request with MTU==MPS. On zephyr this value depend on configured buffer sizes. Since those depends on selected option we just use same fixed value that is configured in IUT.

zephyr: Fix L2CAP/COS/ECFC/BV-04-C

---

autopts/ptsprojects/zephyr/l2cap.py

Eatt connection BTP command is (for whatever reason) in GATT service. Mkae sure GATT service is initialized before calling it.

zephyr: Fix L2CAP/TIM/BV-03-C

---

autopts/wid/gap.py

In that test PTS expects IUT to trigger authentication procedure if GATT read returned auth error in WID 112.

wid: Fix GAP/SEC/AUT/BV-19-C test

---

autopts/bot/common.py

when generating the test case list. Use case used in iut_config/mynewt.py.

bot: common: Handle existing "test_cases" in default config

---

autopts/ptsprojects/boards/nrf53.py

This overlay is not a part of Zephyr's repo.

boards: nrf53: Remove leftover debug-overlay.conf

---

autopts/pybtp/iutctl_common.py

Error was occuring on machines with encoding cp1250:
File "Python\Python310\lib\encodings\cp1250.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf5'
in position 16
1: character maps to <undefined>

iutctl_common.py: Fix encoding error

---

autopts/client.py
autopts/ptsprojects/bluez/gap_wid.py
autopts/ptsprojects/bluez/sm_wid.py
autopts/ptsprojects/mynewt/gap_wid.py
autopts/ptsprojects/mynewt/gatt_wid.py
autopts/ptsprojects/mynewt/gattc_wid.py
autopts/ptsprojects/mynewt/sm_wid.py
autopts/ptsprojects/zephyr/aics_wid.py
autopts/ptsprojects/zephyr/ascs_wid.py
autopts/ptsprojects/zephyr/bap_wid.py
autopts/ptsprojects/zephyr/dis_wid.py
autopts/ptsprojects/zephyr/gap_wid.py
autopts/ptsprojects/zephyr/gatt_wid.py
autopts/ptsprojects/zephyr/ias_wid.py
autopts/ptsprojects/zephyr/pacs_wid.py
autopts/ptsprojects/zephyr/sm_wid.py
autopts/ptsprojects/zephyr/vcs_wid.py
autopts/ptsprojects/zephyr/vocs_wid.py
autoptsclient_bot.py

First init_loggingi() was not called unitl a process reached init_pts() in client.py. Any debug log before the call was skipped. If any error log was called, then all error logs was printed into console output, even after init_logging() call.

bot: Fix startup logging

---

autopts/ptsprojects/zephyr/gatt.py

GATT/SR/GAW/BI-33-C is using first available long write characteristic andrequires <512 bytes of value data. While GATT/SR/GAW/BV-12-C and GATT/SR/GAW/BV-14-C require exactly 512 value data, in those tests PTS is first looking for valid characteristic (via long reads). So to make all tests happy just declare <512 value characteristic first.

zephyr: Fix GATT/SR/GAW/BI-33-C

---

autopts/pybtp/btp/gatt.py

Fix error for format specifier in autopts/pybtp/gatt.py. GATT/CL/GAD/BV-06-C is failing because of this.

Path error for format specifier in gatt.py.

---

autopts/pybtp/btp/gatt.py

Characteristics value_handler rather than handler should be appended to verify values. This change fixs GATT/CL/GAD/BV-05-C.

btp: gatt: wrong chrc handler

---

autopts/wid/wid.py

sys.modules contains already imported modules, but will not import a new one.

wids: Fix wid import in generic wid

---

autopts/wid/bap.py

In TSE24099 we found out that MMI 305 has wrong description and we should assume that the MMI states "Please configure ASE state to Disabling for ..." . The description will be fixed in next PTS release.

bap: Cleanup wid 305

---

autopts/bot/iut_config/mynewt.py

Privacy was not set for this test because of lacking coma in the preceding line.

bot: mynewt: Fix setting privacy for GAP/CONN/ACEP/BV-03-C

---

autopts/wid/gap.py

In this test PTS might ask for disconnection before IUT event with lost bond is processed resulting in random failures.

wid: Improve GAP/SEC/AUT/BV-21-C handling

---

autopts/wid/sm.py

In TS there is no disconnection requirement here. We should confirm that pairing aborted (failed).

SM: fix SM/CEN/PKE/BI-02-C

---

autopts/client.py

If LT1 and LT2 are used in a test case, it is sometimes useful to grep the logs for a specific LT, e.g.:
cat autoptsclient_bot_65000_65002.log | grep LT2 > lt2_logs.log

logs: Add names to LT threads for easier grep

---

autopts/ptsprojects/zephyr/mmdl.py

The element position of the sensor server should be included in the ixit value.

Update IXIT values for sensor server model tests

---

autopts/ptsprojects/zephyr/gatt.py
autopts/wid/gatt.py

This fixes LT2 initialization, missing PTS address and properly implements GATT WID 308 to make Upper Tester match TS requirements.
Test is stil failing due to race in BTP handling but this will be handled in separate PR.

zephyr: Fix GATT/SR/GAN/BV-02-C

---

autoptsserver.py
autoptsserver_requirements.txt

After a PTS recovery request sent by a client, the recovery flag was not cleared. After a server recovery request, the dongle selected during initialization was forgotten, causing the YKUSH to reattach the wrong dongle.

autoptsserver: Fix recovery request

---

autopts/ptsprojects/mynewt/gatt.py
autopts/ptsprojects/mynewt/mesh.py
autopts/ptsprojects/zephyr/aics.py
autopts/ptsprojects/zephyr/ascs.py
autopts/ptsprojects/zephyr/bap.py
autopts/ptsprojects/zephyr/dis.py
autopts/ptsprojects/zephyr/gatt.py
autopts/ptsprojects/zephyr/has.py
autopts/ptsprojects/zephyr/ias.py
autopts/ptsprojects/zephyr/mesh.py
autopts/ptsprojects/zephyr/mmdl.py
autopts/ptsprojects/zephyr/pacs.py
autopts/ptsprojects/zephyr/vcs.py
autopts/ptsprojects/zephyr/vocs.py

Since the auto-pts supports only 64-bit python 3, it can be run only under 64-bit Windows. In that case the default installation directory of the PTS is "C:\Program Files (x86)\Bluetooth SIG", not "C:\Program Files\Bluetooth SIG". Hence the databases set with TSPX_tester_database_file were not loaded and the PTS used its default databases. This did not affect test cases so far, but let's remove those settings to avoid confusion in the future.

pixits: Remove the TSPX_tester_database_file setting

---

autopts/pybtp/btp/bap.py
autopts/wid/bap.py
autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6
doc/btp_bap.txt

After refactor the IUT tester app allows to buffer greater amount of data in a ring buffer. This allows to send series of streaming data that more likely to have sequence numbers without gaps. Python + current BTP implementation does not allow to generate audio data at required intervals.

zephyr: bap: Fix sending ISO data

---

autopts/ptsprojects/boards/nrf53.py

To meet common PTS configuration requirements, the default value of BT_BUF_ACL_RX_SIZE is assigned a fixed value 100. However, it is overwritten as 255 in bttester nrf53 overlay config. Since Zephyr L2CAP COC MPS depends on this config value, several L2CAP qualification test cases are affected, incl. L2CAP/COS/CFC/BV-03-C, L2CAP/COS/ECFC/BV-02-C, L2CAP/COS/ECFC/BV-04-C, L2CAP/ECFC/BV-22-C.
To fix the above failed tests on nrf53, reset the value of BT_BUF_ACL_RX_SIZE to 100 in building.

boards: nrf53: Use fixed value for BT_BUF_ACL_RX_SIZE in overlay

---

autopts/bot/iut_config/mynewt.py

This PR fixes privacy setting for:
GAP/CONN/ACEP/BV-58-C
GAP/CONN/ACEP/BV-61-C
Also, this enables MITM setting in mynewt overlay,
which is required for both of those tests to pass.

bot: mynewt: Set proper secutiry for GAP/CONN/ACEP tests

---

autopts/ptsprojects/mynewt/gatt_wid.py

These were overriding handlers from wid/gatt_client.py, thus using incorrect service.

mynewt: remove remnants of GATT/CL wids from gatt_wid.py

---

autopts/ptsprojects/boards/__init__.py

The implementation of get_free_device is pretty naive and takes a first found COM serial device if only it has any serial number. Because the JLink serial numbers as far were only numeric and recently supported boards has serial numbers with length >=9, we can improve the function a little.

boards: Strict a serial number to be only numeric

---

autopts/ptsprojects/boards/__init__.py
autopts/ptsprojects/stack.py
autopts/ptsprojects/zephyr/iutctl.py
autopts/ptsprojects/zephyr/ztestcase.py

There are tests that restart IUT in the middle which means that event needs to be removed from queue. Otherwise second call returns immediatelly due to old event being present. Since leaving event on queue is unlikely scenario, just change default to always remove it.

zephyr: Fix handling of IUT ready event

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Tests enabled manually, but will be corrected with Launch Studio in the future.

zephyr: Enable CSIS and HAS tests in workspace

---

autopts/ptsprojects/stack.py

Caused BTP ERROR in some test cases for mynewt e.g. GAP/SEC/SEM/BV-26-C.

stack: Restore accidentally removed return statement

---

autopts/ptsprojects/zephyr/iutctl.py

This exception was thrown when no test case prefix was matched, resulting in stack.core not being initialized.
File "C:\Users\magda\auto-pts\autopts\client.py", line 1102, in start
self.cleanup()
File "C:\Users\magda\auto-pts\autopts\client.py", line 1170, in cleanup
autoprojects.iutctl.cleanup()
File "C:\Users\magda\auto-pts\autopts\ptsprojects\zephyr\iutctl.py", line 326, in cleanup
ZEPHYR.stop()
File "C:\Users\magda\auto-pts\autopts\ptsprojects\zephyr\iutctl.py", line 252, in stop
stack.core.event_queues[defs.CORE_EV_IUT_READY].clear()
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'event_queues'

zephyr: iutctl: Fix misguiding exception

---

autopts/ptsprojects/zephyr/gatt.py
autopts/wid/gatt.py

LT1 shall wait at hdl_wid_149 until LT2 will connect to IUT, let's ensure this with SynchPoint feature. Moreover, multiple BTP commands at once from two Lower Testers causes BTP ERRORs. Let's just use thread locks as a workaround for now.

zephyr: gatt: Fix GATT/SR/GAN/BV-02-C

---

autopts/bot/common.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py
autopts/client.py
test/unittests.py

A datetime tag in report txt file name prevents diff view in GitHub, but it is still sometimes useful. To compromise, just add a second same report file, but without a tag.

bot: common: Add report txt without tag to githubdrive

---

autopts/bot/iut_config/zephyr.py

Bot has to apply the overlay-le-audio.conf during build to enable audio features.

zephyr: bot: iut_config: Apply overlay-le-audio.conf for CSIS

---

tools/cron/common.py

clear_workspace deletes any file from workspace folder unless its extension is the exceptions list. The .bls file from nimble workspace was deleted at bot run thus making the autopts repo marked as dirty.

cron: Ignore Launch Studio project file at cleanup

---

autopts/ptsprojects/zephyr/iutctl.py

If cleanup after a test case was successful, then we do not need to stop(reset) the IUT at the end of autopts client run. The BTP socket has already been closed, so there will be no IUT ready event anyway.

zephyr: iutctl: Fix long iut cleanup

---

autopts/bot/common.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py
tools/cron/common.py

Until now, a message about an error was sent only to the admin e-mail. Let's post a comment under a PR that triggered a failing PR job, indicating that the results will not be delivered due to an error.

cron: bot: Post a comment under PR in case of bot failure

---

autopts/bot/common.py

.bls file was moved during the pull and that made the repo marked as 'dirty'.

bot: Ignore .bls file at pull_server_logs()

---

autopts/wid/bap.py

Since PTS 8.5.1 the description of the wid 201 will contain an ID of the required codec configuration, so there will be no need to have a hardcoded list of test cases and their configurations.

bap: Update description parsing of wid 201

---

autopts/bot/common_features/report.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py
tools/cron/common.py

find_latest_db turned out to be not a very good solution. It works fine if githbudrive repo is used only on one machine. Let's just use the .db file configured with 'database_file'. The database still can exist in the githubdrive, so let's update the repo at bot start. The remaining issue with separate .db files will be fixed in the next patches with some merging tool instead.

cron: Use 'database_file' config instead of find_latest_db

---

autopts/ptsprojects/zephyr/aics.py
autopts/ptsprojects/zephyr/ascs.py
autopts/ptsprojects/zephyr/bap.py
autopts/ptsprojects/zephyr/gap.py
autopts/ptsprojects/zephyr/ias.py
autopts/ptsprojects/zephyr/l2cap.py
autopts/ptsprojects/zephyr/micp.py
autopts/ptsprojects/zephyr/pacs.py
autopts/ptsprojects/zephyr/vcp.py
autopts/ptsprojects/zephyr/vcs.py
autopts/ptsprojects/zephyr/vocs.py

PTS profiles contain different sets of pixits and some set_pixit() calls were just copy pasted without checking if a pixit is really available in a profile. This doesn't interrupt a test run, but it clutters the autoptsserver logs a little.

zephyr: pixits: Fix set_pixit() exceptions

---

tools/cron/common.py

Let's just assume that no PASS in a line means failed status.

cron: Fix missing failed statuses

---

tools/cron/common.py

Skip the first line of report.txt, because it contains repos sha.

cron: github: Do not post repo sha in bot results

---

autopts/ptsprojects/zephyr/gatt.py

PTS is not consistent with LT2 naming and some has underscore (_LT2) and some dash (-LT2).

zephyr: Fix GATT/SR/GAS/BV-03-C LT2 test name

---

autopts/ptsprojects/zephyr/mesh.py

For MESH/SR/RPR/LNK/BI-05-C common pre_conditions are enough to run the test case.

zephyr: mesh: correct the precondition for RPR/LNK/BI-05 test

---

autopts/pybtp/btp/mmdl.py
autopts/wid/mmdl.py

Update MMI parameter formats according to latest
PTS version. Update the sensor id with a one supported by PTS.
Fixes:
MMDL/CL/SNR/BV-12-C and MMDL/CL/SNR/BV-13-C

zephyr: mesh: align sensor client tests with latest PTS

---

autopts/pybtp/btp/mesh.py

IV Update Test mode flag is set in bt_mesh.flags:
https://github.com/zephyrproject-rtos/zephyr/blob/7fb2929e5ba058da82716b6555f75c112c252072/subsys/bluetooth/mesh/net.c#L248-L250 which is reset when bt_mesh_reset() is called:
https://github.com/zephyrproject-rtos/zephyr/blob/7fb2929e5ba058da82716b6555f75c112c252072/subsys/bluetooth/mesh/main.c#L341-L352
If hdl_wid_13 has been called at the start of the test and stack.mesh.is_provisioned.data was set, btp.mesh_reset() will be called, which will reset the flag. Therefore we need to restore it after resetting the stack.

mesh: Restore IV Update Test mode after reset

---

autopts/wid/mmdl.py

This PR enables support for Pull mode MBT tests:
- MBT/SR/BT/BV-05-C
- MBT/SR/BT/BV-07-C
- MBT/SR/BT/BV-08-C
- MBT/SR/BT/BV-10-C
This PR also allows to run them with friendship, but currently disables LPN on the node as the tests fail.

mesh: Add handlers for MMIs 303, 304 and 346 needed for MBT tests with Pull mode

---

autopts/ptsprojects/testcase.py

Some wids do not follow convention by returning a value of a differrent type than Boolean. In that case the idea about returning post-wids to run next in a tuple was unfortunate. Lets use a special class for this.

testcase: Use ResponseWithPostWID class instead of tuple

---

autopts/ptscontrol.py
autopts/ptsprojects/testcase.py

Some WIDs return a Cancel response to select a different test variant. Let's use a different key word, END_TEST_CASE, to block sending next MMIs to the autopts client.

ptscontrol: Do not close PTSSender on Cancel response

---

autopts/ptsprojects/mynewt/gap.py

TSPX_conn_update_slave_latency is TSPX_conn_update_peripheral_latency now. TSPX_advertising_data cannot be empty and is set later.

nimble: remove invalid PIXIT

---

autopts/client.py

Mistake introduced with 1105383ced7a3c58d9c6f22b8a360a4b21230cd1

bot: Do not select builtin server if server_args is None

---

autopts/ptsprojects/boards/nrf53.py

HCI driver files were renamed in Zephyr repo.

boards: nrf53: Rename hci_rpmsg to hci_ipc

---

autopts/bot/common.py
autopts/bot/zephyr.py
autopts/client.py
autopts/ptscontrol.py
autopts/ptsprojects/mynewt/gatt.py
autopts/ptsprojects/zephyr/bap.py
autopts/ptsprojects/zephyr/gatt.py
autopts/ptsprojects/zephyr/micp.py
autopts/ptsprojects/zephyr/mics.py
autopts/ptsprojects/zephyr/vcp.py
autopts/pybtp/iutctl_common.py
autopts/utils.py
autopts/wid/bap.py
autoptsserver.py
cliparser.py

If interrupt was sent after Superguard timeout and a wid was badly implemented, e.g. in a blocking way, it was possible to end up with multiple BTPWorker threads.

cleanup: Wait for LT threads to finish after interrupt

---

autopts/ptsprojects/mynewt/mesh.py

This is needed because advertising is now enabled via mesh_start. Mesh init only initialises stack now.

mynewt: add Mesh init to preconditions

---

autopts/client.py
autopts/ptsprojects/stack.py
autopts/ptsprojects/testcase.py

and break LT thread barrier in case there was a Superguard timeout. Fixes a case where at retrying a test case the LT threads were waiting at two different SynchPoints, because there was an old wid in step queue.

client: Clear the wid queue before retrying a test case

---

autopts/ptsprojects/testcase_db.py

If there was a new test case and its entry was not in the database, the handle to the database remains open until the garbage collector would eventually close it. Before that the .db could not be moved.

testcase_db: Fix missing close of .db handle

---

autopts/ptsprojects/zephyr/gatt.py

Make PTS use EATT for running GATT tests.

zephyr: Prefer EATT for GATT tests

---

autopts/ptsprojects/zephyr/mcp.py
autopts/pybtp/btp/mcp.py
autopts/wid/mcp.py

Adding missing handler for MCP/SR/SP/BV-01-C testcase. Although this is MCP testcase, it uses Generic Media Control Service - merge after [PR#1054](https://github.com/auto-pts/auto-pts/pull/1054)

zephyr: tester: MCP tests

---

autopts/rtt.py

Some logs were truncated because of the limit equal to the default terminal size. The size cannot be too large though due to  timestamp being aligned to the right.

btmon: Increase output width

---

autopts/wid/gap.py

Despite PTS WID descriptionIUT is expected to advertise without General Discoverable flag set.
This was affecting GAP/BROB/BCST/BV-05-C.

Fix GAP WID 1000 handler

---

autoptsclient-zephyr.py

Workaround for Exception: unknown encoding: idna that appears randomly in embedded Python distribution.
Fixes #1021.

Fix Exception: unknown encoding: idna

---

autopts/bot/iut_config/zephyr.py

To enable CCP tests in the bot runs.

zephyr: Add CCP to overlay-le-audio.conf

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Turn off ICSes: 33a/2, 33a/4, 33a/5, 33a/6 and 33a/8, because the Zephyr Host does not allow the client to establish a CIS in the QoS Configured state.

zephyr: Update PTS workspace

---

autopts/client.py
autopts/ptsprojects/stack.py
autopts/ptsprojects/testcase.py
autopts/pybtp/btp/gap.py
autopts/wid/bap.py
autopts/wid/gap.py
autopts/wid/mcp.py
autopts/wid/micp.py
autopts/wid/sm.py
autopts/wid/vcp.py

In a test case with multiple LTs, if one of LTs has ended its test case with a failed status, there is no need for the other one to wait any longer at the barrier or to run the remaining test case steps.

synch: Stop all LTs if one of LTs failed its test case

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Zephyr controller does not support the PAST procedure, so it will not be able to transfer SyncInfo to Scan Delegator.

zephyr: Update workspace to turn off the BAP/BA/BASS/BV-08-C

---

cliparser.py

Fixes 'board' option help description:
before:
-b BOARD_NAME, --board BOARD_NAME
Used DUT board. This option is used to select DUT reset command that is run before each test case. If board is not specified DUT will not be reset. Supported boards: {'option_strings': ['-b', '--board'], 'dest': 'board_name',
'nargs': None, 'const': None, 'default': None, 'type': None, 'choices': None, 'required': False, 'help': 'Used DUT board. This option is used to select DUT reset command that is run before each test case. If board is not
specified DUT will not be reset. Supported boards: %s. ', 'metavar': None, 'container': <argparse._ArgumentGroup object at 0x7f05d86a86b0>, 'prog': 'autoptsclient-mynewt.py'}.
after:
-b {dialog_da1469x_dk_pro,nordic_pca10056,nordic_pca10095}, --board …

cliparser: Fix -b/--board option help printout

---

autopts/bot/iut_config/zephyr.py

HAP test cases require the audio overlays.

zephyr: iut_config: Add HAP to overlay-le-audio.conf

---

autopts/ptsprojects/stack/layers/gattcl.py

A patch that splitted Stack class has missed star operators.

stack: Fix gattcl.py

---

autopts/wid/ccp.py

Fixing invalid description parsing in MMI handler.

zephyr: ccp: CCP client tests

---

autoptsserver.py

Fix the exception:
"Win32 exception occurred releasing IUnknown"
that occured at close up of the autoptserver.py process. CoInitialize and CoUninitialize should be called only in threads other that the MainThread.

autoptsserver: Fix Win32 exception

---

tools/sort_workspace_projects.py

We've created some PTS Workspaces manually over time and PTS keeps the order in which Profiles/Protocols are added, which leads to an unsorted list. This script sorts the "projects" in a .pqw6 PTS workspace.

tools: add script to sort projects in PTS Workspace by name

---

autopts/ptsprojects/zephyr/gap.py
autopts/wid/gap.py

This PTS test is very fragile with this test and any unexpected pairing causes PTS to fail test (via SMP timeout).
This seems to be an issue on PTS side andthis patch is merely a workaround for PTS issue and thus MMI handling should be reworked when PTS fix its implementation.

zephyr: Fix GAP/SEC/AUT/BV-25-C test

---

autopts/wid/gap.py

PTS seems to send WID 108 twice in a row in this test just with different deciption. This results in calling BTP Pair command twice. On Zephyr second call is just a NOP (since encryption is already enabled), but in NimBLE this results in re-encrypting link with existing LTK which confuses PTS due to unexpected HCI event.

Fix GAP/BOND/BON/BV-02-C

---

autopts/wid/bap.py

The test case was randomly failing because two adverts with different announcement types were started.

zephyr: bap: Fix BAP/USR/ADV/BV-01-C

---

autopts/ptsprojects/zephyr/dfu.py
autopts/ptsprojects/zephyr/mbt.py
autopts/ptsprojects/zephyr/mesh.py
autopts/ptsprojects/zephyr/mmdl.py
autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6
errata/zephyr.yaml

Mesh is by default support v1.1 currently. In this regard
this commit updates the workspace to reflect supported
features. Also MBT 1.0 and DFU 1.0 models and features
supported by Mesh stack are enabled.
Adding the errata for mesh
MESH
Mesh v1.0.1 is dropped and Mesh v1.1 is now selected.
Added features and models:
- Provisioning algorithm ECDH_P256 + HMAC_SHA256 + CCM_AES128.
- Node Provisioning Protocol Interface.
- Node address and composition refresh procedures.
- Private beacon server and client models.
- Remote provisioning server and client models.
- Composition data page 1 and 2.
- On-demand proxy server and client models.
- Solicitation PDU RPL configuration server model.
- SAR configuration server and client models.
- Opcodes aggregator server and client models.
- Large …

Update pts workspace for mesh

---

autopts/pybtp/btp/tbs.py

Change order of data packing. This caused BTP error on tests with prefix GTBS/SR/CP and TBS/SR/CP

zephyr: tester: Fix TBS command

---

autopts/utils.py
autoptsserver.py

If multiple YKUSH boards are plugged in, we need to provide the serial number of the board to be able to reppluged the right PTS dongle. Let's extend the --ykush command so it allowed usage like
--ykush YKUSH_SRN:YKUSH_PORT
Example:
python ./autoptsserver.py -S 65000 65002 --ykush YK12345:1 YK12345:2

autoptsserver: ykush: Allow ykush board selection

---

autopts/ptsprojects/mynewt/gatt_client_wid.py
autopts/ptsprojects/stack/layers/gattcl.py
autopts/wid/gatt_client.py

Mynewt now writes EATT supported wid on encryption changed, not connection event.

Mynewt: fix writing EATT supported bit

---

autopts/ptsprojects/stack/layers/ias.py

This commit adds missing asterisks to arguments in IAS methods. This is a leftover from PR #1093.
Fixes IAS/SR/SP/BV-01-C, IAS/SR/CW/BV-01-C, HAP/HA/DISC/BV-04-C

zephyr: ias: fix IAS methods

---

autopts/ptsprojects/zephyr/csip.py
autopts/wid/csip.py

Add csis register to CSIP preconditions. This is needed to generate adv packets with correct SIRK type. 
Fixes CSIP/SR/SP/BV-01-C, CSIP/SR/SP/BV-03-C
Note: requires https://github.com/zephyrproject-rtos/zephyr/pull/70783 to be merged

zephyr: csip: fix CSIP/SR test

---

autopts/wid/ccp.py

Add CCP/CL/SPE/BI-03-C to tbs_testcases list - this applies proper instance index (TBS) when writing to Call Control Point. Fixes CCP/CL/SPE/BI-03-C

zephyr: ccp: fix CCP wid

---

autopts/bot/common.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py

If the build or flash step for an iut config has failed, set status of its test cases to BUILD_OR_FLASH ERROR and proceed with the next iut config.

bot: Add BUILD_OR_FLASH ERROR

---

autopts/bot/common.py
autopts/ptsprojects/boards/__init__.py
autopts/ptsprojects/mynewt/iutctl.py
autopts/ptsprojects/zephyr/iutctl.py
cliparser.py

jlink.exe randomly crashes the Windows OS. Let's try pylink reset instead.

boards: Add pylink reset

---

.github/workflows/check_pr_changes.yaml

For some reason if: github.run_number == 1 blocked this workflow job. Now, the action will only run when a pull request is opened or converted from draft to ready for review.

ci: Remove unnecessary context variable from workflow file

---

autopts/wid/gmcs.py

This commit implements missing wid. It's appearance is a result of changes from https://github.com/zephyrproject-rtos/zephyr/pull/71679.
Remove stale issues from zephyr.yml related to OTS test cases.

gmcs: wid: add missing WID

---

autopts/ptsprojects/zephyr/mesh.py

Commit fixes SAR client tests.
SAR client suppose to use device key of remote device. Only provisioner knows such keys and keeps them in CDB.

mesh: fix sar client tests

---

autopts/ptsprojects/zephyr/mmdl.py

Use correct api to set pixit value for mmdl.

zephyr: mesh: mmdl: use correct api to set pixit

---

autopts/client.py

Result of the last test case before next rebuild was printed after the rebuild, e.g.:
...
31/32   MBT     MBT/CL/BT/BV-07-C   PASS           38.097
32/32   MBT     MBT/CL/BT/BV-08-C   -- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
...
Applying pin reset.
-- runners.nrfjprog: Board with serial number 683511993 flashed successfully.
PASS           31.924

bot: Fix print of the last test case result

---

autopts/bot/common.py
tools/cron/autopts_cron.py
tools/cron/common.py

If a magic tag command does not contain a name of a board that should be used for AutoPTS testing, automatically assign tests to the correct boards.

tools: cron: pr: Auto assign tests to the correct board

---

tools/cron/github_cron.py

Take the login of repo owner instead of the login of the PR creator.

tools: github_cron: Fix fetch of repo owner

---

autopts/ptsprojects/zephyr/csip.py
autopts/pybtp/btp/csip.py
autopts/wid/csip.py
doc/btp_csip.txt

- Add address_count and addr array parameters to set_lock and set_release btp commands.
- Code cleanup for readability
- Preconditions adjustment
Fixes FATAL ERROR in CSIP/CL/SP/BV-07-C, CSIP/CL/SP/BV-03-C, CSIP/CL/SP/BV-04-C, CSIP/CL/SPE/BI-01-C
Merge after https://github.com/zephyrproject-rtos/zephyr/pull/71059

zephyr: csip: set member lock/release command refactor

---

autopts/ptsprojects/mynewt/gatt.py
autopts/wid/gatt_client.py
errata/mynewt.yaml

- Adjust gatt client wid handler
- Enable EATT for GATT tests. This triggers PTS Issue (added specific test cases to mynewt errata list) - PTS database is missing Server Supported Features Charateristic.
Related - https://github.com/apache/mynewt-nimble/pull/1787, 
https://github.com/apache/mynewt-nimble/pull/1791

mynewt: Enable EATT for GATT tests

---

autopts/wid/cap.py

Add missing WIDs for CAP/COM/CRC tests
btstack/cap.py is here: https://github.com/bluekitchen/auto-pts/blob/develop-le-audio-broadcast/autopts/ptsprojects/btstack/cap.py

Support CAP Capturing and Rendering Control Procedures

---

.github/workflows/check_pr_changes.yaml

This seems to be needed now when GITHUB_TOKEN is used.

ci: Fix permissions for posting comments in PRs

---

cliparser.py
tools/cron/autopts_cron.py
tools/cron/common.py
tools/cron/estimations.py

By using test_case_limit param when triggering cron, we can limit number of test cases to be run when passing only test case prefix (e.g. GATT, GAP)

tools: cron: add test_case_limit param

---

autopts/ptsprojects/mynewt/gatt_client_wid.py

Add missing argument to mynewt wid_hdl to avoid
"TypeError: hdl_wid_() takes 0 positional arguments but 1 was given"

mynewt: wid: add missing argument to wid_hdl

---

tools/list_testcases.py

This was causing script to not being able to locate required imports.

tools: Fix repo path in list_testcases

---

tools/cron/common.py

It happened that the TCP/IP socket of the server got stuck, so lets restart the process at each cron job.

cron: Add start of an active hub server

---

autopts/ptsprojects/zephyr/dis.py

So far GATT service was used to create DIS but we should use one from Zephyr.

zephyr: Use builtin DIS service

---

tools/cron/autopts_cron.py
tools/cron/estimations.py

This will enable to run specified amount of test cases from among prefixes (when there is more than one) that are used with magic tag.

tools: cron: improve test case limit parameter

---

autopts/bot/common.py
autopts/client.py

The loaded tc stats were not inited with tc database, hence regressions could not be caught if the autopts bot was restarted in the meantime.

bot: Load missing tc database into stats backup

---

autopts/utils.py
tools/cron/common.py

Rarely, but it happens that restart of the testing setup fails, e.g. because of some TCP/IP socket. Let's try restart the bot setup again if bot terminated unexpectedly.

cron: Restart bot again in case of timeout

---

autopts/ptsprojects/mynewt/gatt_client_wid.py

Adding gap_pair in wid_142 fixes various GATT/CL testcases. It may be that PTS used to (before some update) initiate pairing procedure which is why no btp command was used in this handler.
Fixes GATT/CL/GAN/BV-02-C GATT/CL/GAR/BI-36-C GATT/CL/GAR/BI-38-C GATT/CL/GAR/BI-44-C GATT/CL/GAR/BV-08-C GATT/CL/GAR/BV-10-C GATT/CL/GAT/BV-03-C

mynewt: gatt: add btp gap pair command

---

autopts/ptsprojects/zephyr/dis.py

Fixes [issue 1227](https://github.com/auto-pts/auto-pts/issues/1227).

zephyr: fix wrong DIS PIXIT value

---

autoptsclient_bot.py
tools/cron/autopts_bisect.py
tools/cron/common.py

A .py file loaded as a module is cached until it is explicitly removed from sys.modules. So subsequent attempts to load the file only return a reference to the existing module-dictionary. So we need to deep-copy a config.py to prevent overwriting its original values and reuse it e.g. in subsequent PR jobs.

tools: cron: fix cron

---

autopts/bot/common.py
autopts/bot/zephyr.py
autopts/ptsprojects/boards/__init__.py
autopts/ptsprojects/boards/nrf53_audio.py
autopts/ptsprojects/zephyr/iutctl.py

Adds the nRF5340 audio devkit board, with capabilities to build both application and network cores with configurable separate builds.

zephyr: Add support for the nRF5340 Audio devkit

---

autopts/bot/common.py
autopts/client.py
autopts/config.py
autopts/ptsprojects/boards/nrf53_appcore.py
tools/cron/common.py

Minor fixes:
- fix missing descriptions in report emails,
- fix generating redundant folder with session logs and old logs,
- in backup mode, prevent restarting bot by cron if logs pulling takes longer than cron timeout
- add config for building/flashing only appcore of nrf53

 cron: Fix missing descriptions in report emails

---

autopts/ptsprojects/zephyr/cap.py

CAP WIDs are using MICP and VCP commands and thus shall initialize required BTP services.

zephyr: Fix multiple CAP/INI/UST tests

---

autopts/ptsprojects/mynewt/gatt_client_wid.py

Currently there is no way to access included service handle in Nimble with find included services procedure. We still can use other values that we have access to, to compare them with values from MMI which should be enough to pass test GATT/CL/GAD/BV-03-C.

mynewt: gatt_cl: add mynewt specific wid handler

---

autopts/bot/common.py

Fixed a typo that caused the .xlsx report to contain the contents of the .txt report.

bot: Fix path to .xlsx report

---

autopts/ptsprojects/mynewt/mesh.py
autopts/ptsprojects/zephyr/mesh.py

It is possible that setup has more than two PTSes available and invalid check was causing those to be skipped. Follow early return pattern as other profiles as this is future proof.

Fix two PTSes tests for MESH

---

autopts/wid/gap.py
autopts/wid/gatt.py
autopts/wid/gatt_client.py
autopts/wid/sm.py

Some string used for regex were not using Python raw string (`r""`). This may cause problems when the regular expression use backslash. Python would try to interpret the backslash as an escape sequence.

Use raw string for regex

---

autopts/bot/zephyr.py

The wrong key was used to access error file path. This caused unhandled exception.

Replace key 'error_txt' with 'ERROR_TXT_FILE'

---

autopts/wid/bap.py

Those WIDs are send for both LT and LT2. To properly validate we must check only for specific lower tester.

wid: Fix WID 364 and 366 handlers in BAP

---

errata/zephyr.yaml

Not all tests initially affected by 2 ISOs connection issues are passing but those are no longer related to it.

errata: Cleanup fixed Zephyr specific erratas

---

autopts/wid/tmap.py

This PR provides minor fixes and the missing WIDs to pass all TMAP tests for LE-only (we ignore GATT over BR/EDR so far).
Test configuration for the BTstack PTS Project can be found here: https://github.com/bluekitchen/auto-pts/blob/develop-le-audio-tmap/autopts/ptsprojects/btstack/tmap.py

Add missing TMAP WIDs

---

autopts/ptsprojects/stack/layers/gap.py
autopts/wid/gap.py

This commit implements a temporary workaround for PTS issue 136305 which causes invalid sequence of events in some GAP/SEC/SEM test cases. There are two conflicting MMIs that affect test case verdict when handled in incorrect order.

wid: gap: Add workaround for conflicting MMIs

---

cliparser.py

This PR allows to specify multiple test case (prefixes) to run, e.g `-c GMAP/UGG/LLU/BV-05 -c GMAP/UGG/LLU/BV-06'

cliparser: allow to use option -c multiple times to specify list of test cases

---

autopts/ptsprojects/zephyr/l2cap.py

After updating workspace to PTS 8.7.2 the TSPX_inmtu is renamed to TSPX_l2ca_inmtu. Fixes the exception:
xmlrpc.client.Fault: <Fault 1: "<class 'autopts.ptscontrol.BadPixitException'>:
L2CAP TSPX_inmtu 02A0:\nPTSCONTROL_E_PIXIT_PARAM_NOT_FOUND">

zephyr: Fix pixit name

---

autopts/ptsprojects/boards/nrf54l.py

updating the board type for nrf54l family as nrf54l15dk

boards: update nrf54l board type to nrf54l15dk

---

.gitignore

Added venv and .venv which are common names for
python virtual environments to the gitignore.

Added python venv to gitignore

---

.gitignore

The tmp directory is creating during manual testing and should never be pushed.

Add tmp to gitignore

---

autopts/wid/tmap.py

Fix following:
autopts/wid/tmap.py:718: SyntaxWarning: invalid escape sequence '\d'

wid: tmap: Use raw string for regex

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This was due to bug in Qualification Workspace.

zephyr: mesh: Fix missing MBTM and DFUM profiles

---

autopts/wid/csip.py

The test also requires discovery and was failing due to this. Re-arranged the list of tests to be in alphabetical order to make it easier to follow.

csip: Add CSIP/CL/SP/BV-07-C to list of tests for CSIP discovery

---

autopts/bot/zephyr.py
autopts/ptsprojects/boards/nrf52_wsl.py
autopts/ptsprojects/boards/nrf53.py
autopts/ptsprojects/boards/nrf53_appcore.py
autopts/ptsprojects/boards/nrf53_audio.py
autopts/ptsprojects/boards/nrf54h.py
autopts/ptsprojects/boards/nrf5x.py

OVERLAY_CONFIG was deprected in Zephyr 3.4:
https://docs.zephyrproject.org/latest/releases/release-notes-3.4.html#build-system-and-infrastructure

bot/zephyr: Use EXTRA_CONF_FILE instead of OVERLAY_CONFIG

---

autopts/ptsprojects/zephyr/cap.py

The following tests require 2 CCIDs, and are failing if the device does not have have 2 CCIDs registered:
CAP/INI/BST/BV-07-C
CAP/INI/BST/BV-10-C
CAP/INI/UST/BV-13-C
CAP/INI/UST/BV-14-C
CAP/INI/UST/BV-27-C
CAP/INI/UST/BV-28-C
CAP/INI/UST/BV-31-C
CAP/INI/UST/BV-36-C
CAP/INI/UST/BV-37-C
CAP/INI/UTB/BV-04-C

cap: Register TBS to have 2 CCIDs registered

---

errata/common.yaml

The Request ID 147314 applies to nearly all tests that uses multiple lower testers, as it affects how IRKs are handled by PTS.

errata: Add Request ID 147314 for CSIP and more

---

autopts/client.py

When running autoptsclient-zephyr.py --help, traceback was printed in terminal. 
This was caused by logging.exception(e) which should not be called when exiting with status 0.

client: adjust exception logging

---

autopts/client.py

There is no point in repeating test case if MISSING WID ERROR is returned.

client: ignore retry param for MISSING WID ERROR

---

autopts/pybtp/btp/cap.py
autopts/wid/cap.py
doc/btp_cap.txt

Modified the hdl_wid_312 handler to call cap_unicast_audio_stop with release = False, so that it performs a disable (and stop) without release.
Why PTS wants us to disable first is unclear, as the test spec states to release, which would be handled by hdl_wid_309.
This is required by https://github.com/zephyrproject-rtos/zephyr/pull/79674

zephyr: Fix cap.hdl_wid_312 to use cap unicast stop

---

autopts/ptsprojects/boards/nrf53.py
autopts/ptsprojects/boards/nrf53_appcore.py
autopts/ptsprojects/boards/nrf53_audio.py
autopts/ptsprojects/boards/nrf54h.py

Using sysbuild, cpuapp build automatically triggers building hci_ipc build for cpurad. Preserve the old behaviour for 53 with no sysbuild.

zephyr: sysbuild configuration for 53/54h

---

autoptsserver.py

- There is no print when a KeyboardInterrupt is recieved This PR adds prints so the user knows the server is alive and in the process of terminating

Print on Ctrl-C

---

autopts/bot/iut_config/zephyr.py

Aligning the bot for mesh blob client tests with zephyr tester.
https://github.com/zephyrproject-rtos/zephyr/pull/81531

bot: zephyr: separate blob client test configuration

---

autopts/ptsprojects/zephyr/tmap.py
autopts/wid/tmap.py

- Add missing init and register of cap
- Always release previous streams before starting new

tmap: Fix failing TMAP tests BMS/ASC/BV-01 and BV-02

---

autopts/ptsprojects/zephyr/cap.py
autopts/wid/cap.py

16_2_1 is the mandatory configuration from BAP so it is supported by all platforms.

Zephyr: CAP: Change to use 16_2_1 by default

---

autoptsserver.py
autoptsserver_requirements.txt

- Check has been added to ensure that the selected com port(s) exist. pyserial was used as it was much faster than wmi

server: Check that COM port exists

---

autopts/pybtp/btp/gatt.py

There were couple typos in BTP GATT after mass rename.

btp: Fix typos in GATT service

---

autopts/client.py

Add a small sleep between each lower tester thread for the CSIP tests that has an IRK duplication issue.
This is not meant to be a proper solution, but a workaround until a better solution can be found.

client: Add sleep for CSIP tests with multiple LTs

---

autopts/ptsprojects/zephyr/hap.py

cap_unicast_setup_ase was called  in hdl_wid_482 without registring cap which resulted in BTP Error with opcode Unknown Command. Test still fails occasionally and will require further investigation.

hap: fix BTP ERROR in HAP/HAUC/STR/BV-01-C

---

autopts/wid/cap.py

For some reason VCP discovery wasn't called in wid handler where cap, bap and micp are discovered. This caused vcp procedures being called before VCP discovered event has been received. Also added wait for vcp procedure ev after some vcp procedures in wid 20106.
Fixes BTP ERROR in test cases: CAP/COM/CRC/BV-01-C, CAP/COM/CRC/BV-03-C CAP/COM/CRC/BV-04-C

wid: CAP: move vcp discovery to wid 20100

---

autopts/bot/iut_config/zephyr.py

CONFIG_SECURE_STORAGE=y is currently required to be explicitly enabled when CONFIG_BT_SETTINGS=y is set.

zephyr: Fix MESH storage configuration

---

autopts/ptsprojects/stack/layers/mcp.py
autopts/wid/mcp.py

Do discovery only when asked to do it and avoid hardcoded ATT handles in WIDs.

wid: MCP: Rework some handlers for more explicit actions

---

autopts/bot/common_features/report.py

Add a note to report.txt, that logs may not be available for a test case with TIMEOUT result. The TIMEOUT result means that the autopts bot was externally terminated, because a test case took too long and the bot failed to recover PTS. If backup mode is enabled, the bot can be restarted to resume the test run. Since the PTS was forcefully terminated and the faulty test case will not be rerun by the bot, the test case logs will most likely not be available.

bot: report: Add a note for TIMEOUT result

---

autopts/bot/common.py
autopts/bot/common_features/mail.py

AutoPTS test session result email will now contain a table underneath summary section that includes statistics regarding each test group - e.g. AICS - 19 test runs, 19 Passed, 0 Failed, 100% Pass rate

bot: email: add test suite summary

---

autopts/bot/iut_config/zephyr.py

Central Address Resolution characteristic is present only with BT_PRIVACY enabled.

zephyr: Add GAP/GAT/BV-18-C to privacy enabled group

---

autopts/ptscontrol.py

When autoptsserver is launched and there is no PTS dongle connected, PTS will restart indefinitely. Implemented solution will now display warning after 5 iterations and terminate all processes.
Fixes https://github.com/auto-pts/auto-pts/issues/1308

autoptsserver: fix infinite restart

---

tools/cron/common.py

This job can be used before weekly runs to make sure newt is up to date to avoid build or flash error

tools: cron: add newt update job

---

autopts/bot/common.py
autopts/bot/common_features/mail.py

Previously implemented profile_summary function is now used to write to readme.md file in Github logging repo and AutoPTS
test session result email. Table width is now adjusted to be displayed properly on various screens

bot: report: add test group summary to readme.md

---

autopts/ptscontrol.py

NULL pointer is acceptable for any negative response which includes No and Cancel.

ptscontrol: Return NULL for any negative response

---

autopts/wid/mcp.py

This ID is later used in WID 20121.

wid: MCP: Fix storing object_id in WID 20107

---

autopts/ptsprojects/zephyr/tmap.py
autopts/wid/tmap.py

- Adjust TMAP preconditions - Calling BTP Commands with uninitialized svcs causes BTP ERROR in TMAP/CG/VRC/ test cases. 
- Adjust wid handlers - wid_504_settings dictionary is adjusted accordingly to newest test case naming. WID 20107 which handles reading characteristics should use profile api.
related - https://github.com/zephyrproject-rtos/zephyr/pull/83456

TMAP: Fix various issues

---

autopts/ptsprojects/mynewt/gatt.py

Previous test procedure didn't use SynchPoint,
thus invalid timings in test behaviour occured.

Add SynchPoint for GATT/SR/GAN/BV-02-C

---

autopts/ptsprojects/stack/layers/pbp.py
autopts/ptsprojects/zephyr/__init__.py
autopts/ptsprojects/zephyr/pbp.py
autopts/ptsprojects/zephyr/pbp_wid.py
autopts/wid/pbp.py

This adds code for testing the PBP feature for the Zephyr project on broadcast source. This is done in conjunction with a PR in the Zephyr repository.
See https://github.com/zephyrproject-rtos/zephyr/pull/82654

zephyr: wid: btp: Add files for PBP source testing

---

autopts/ptsprojects/mynewt/mesh.py
autopts/ptsprojects/zephyr/mesh.py

This is a leftover from BTP_CMD and BTP_EV variable names refactor.
Fixes https://github.com/auto-pts/auto-pts/issues/1369

mesh: remove deprecated opcode

---

autopts/bot/iut_config/zephyr.py

Missing colon was causing DFUM/CL/FU tests to be build without required overlay.

bot: zephyr: Fix tests matching for mesh_dfd_srv.conf overlay

---

autopts/bot/common.py
tools/cron/common.py

ERROR_TXT_FILE will be written to when invalid PIXIT name or value is set. We check for this file in _run_test function from cron to stop it from restarting indefinitely.
Fixes https://github.com/auto-pts/auto-pts/issues/1377

tools: cron: stop cron in case of error

---

autopts/ptsprojects/zephyr/cap.py

- Add ternary operation to start adv when tc_name includes CAP/ACC
- Move bd_addr IXIT update to pre_conditions as this was done for all tests
- Fixes regression for CAP/INI/BST tests

CAP: Only adv as precondition when CAP/ACC

---

doc/btp_gap.txt

Proposal to add gap_set_rpa_timeout command, which would enable dynamically changing rpa timeout.
I've used 0x30 opcode to respect  #1368.

doc: btp_gap: Adds set rpa timeout

---

autopts/bot/common.py
autopts/bot/common_features/report.py
autopts/client.py

Fixed:
https://github.com/auto-pts/auto-pts/issues/1380
[Issues1380] Add execution time to the report xlsx
and
https://github.com/auto-pts/auto-pts/issues/1381
[Issues 1381] Split test results columt to an actual result only and extra comment if applicable
Add 4 columns to xlsx report xlsx
Result Additional Info | Start Time | End Time | Duration
changes:
added a function to find xml files,
safer retrieval of values to sxclude KeyError,
added a function that parses 'Result' data into 2 columns(Tuple),
handling potential exceptions
Cosmetic Changes:
clearer nomenclature,
Example:
[example_report.xlsx](https://github.com/user-attachments/files/18904421/example_report.xlsx)

bot: report:  Add 4 columns to xlsx report

---

autopts/ptsprojects/mynewt/l2cap.py

L2CAP service is needed only for CoC testing. Also cleanup some custom tests that were using default configuration anyway. This allows to run fixed channels related tests without CoC enabled.

nimble: Clean up L2CAP project

---

autopts/client.py
errata/common.yaml

The fix has been incorperated in PTS and the errata list and the sleep workaround has been updated.

errata: Remove CSIP errata and sleep

---

autopts/wid/bap.py

- Due to refactoring of PR#1366, an extra argument got left behind

BAP: Remove straggling broadcast_id

---

autopts/ptsprojects/zephyr/bap.py
autopts/wid/bap.py

- Add custom case for BAP/BSRC/SCC/BV-38-C to set broadcast_ID
- Fixes regression for BAP/BSRC
- These get a random broadcast_ID, so the IXIT value should not be set

Only set broadcast_ID for SCC/BV-38-C

---

autopts/wid/gatt.py

Those tests require non-bonding pairing if EATT is in used. WID 130 is used to ensure that no previous bond is present on IUT. Use it to tune IUT to non-bondable mode until ES-27410 is incorporated.

wid: Fix GATT/SR/GAI/BV-01-C and GATT/SR/GAN/BV-01-C

---

autopts/wid/csip.py

PTS can be sloppy with requesting pairing from IUT for CSIP tests, being a particular problem in CSIP/CL/SP/BV-07-C. With unfortunate timing this can lead to the IUT never receiving a pairing-request from a lower tester, and with some controllers this happens consistently. This commit forces the IUT to initiate pairing, regardless of a request from the lower tester being received or not.

Force pairing for CSIP tests

---

autopts/bot/common_features/report.py

This PR adds support for the .btt file extension in the _pull_logs function to prevent errors related to file access conflicts during report cleanup.
The error occurred because .btt files—generated by the Ellisys Bluetooth Analyzer in the background—were not excluded from deletion, causing permission issues when they were still in use by the analyzer.
Example of the error:
xmlrpc.client.Fault: <Fault 1: "<class 'PermissionError'>:[WinError 32] The process cannot access the file because it is being used by another process: '...GAP_BROB_BCST_BV_04_C_2025_03_24_14_23_13.btt'">

autopts: bot: common_features: report.py

---

tools/cron/autopts_cron.py

Previously a magic tag without test cases specified was ignored. Now a default list of test cases can be specified to perform a smoke test.

cron: magic_tag: Use default_test_cases if prefixes not provided

---

autopts/ptsprojects/stack/stack.py
autopts/pybtp/btp/btp.py
autopts/pybtp/common.py

Implementation:
[Issues 1251] Start using 'Read supported commands' 
#1251 
As part of this pull request, a new function has been added to verify whether the registered commands are supported by the system. This function has been integrated with the existing command registration mechanism, so that at the time of registration, each command is immediately checked for its support.
Additionally, an indication of the correct way to invoke supported commands has been introduced, which makes it easier for the user to use the system correctly and reduces the possibility of errors.

AutoPts: btp: Start using 'Read supported commands'

---

autopts/ptsprojects/boards/nrf53.py

Update the nrf53.py file so that it uses sysbuild rather than explicitly building the network and application core separately.

boards: Use sysbuild for nrf53

---

tools/cron/autopts_cron.py

The final list of test cases was not overwritten with the filtered list.

cron: pr job: Fix per commit limit

---

autopts/wid/gatt.py

The `value_read` variable is converted to a string in the if branch but not in the else one where it's still `bytes`. The `decode` method later called on `value_read` is trying to convert it to a string. But in the case we were in the if branch, `value_read` is already a string. This lead to an `AttributeError` because the `decode` method doesn't exist for string.
Introduce `value_read_str` variable to fix the issue. That variable will be used to convert `value_read` in each branch to a string.

Fix `hdl_wid_52` decode error

---

doc/btp_gap.txt

Add "use filter accept list" flag to Start Discovery.
Previously the BTP specification did not really say whether or not the filter accept list should be used for scan results.
This caused some confusion at least on our end, as we expected the accept list to apply for scanning as well. Now the application can explicitly say whether it wants to use the filtering or not. Any existing implementations that don't parse this flag will continue to behave the same way they used to, so this shouldn't cause backwards compatibility problems.

doc/btp_gap: add filter accept list flag to discovery

---

autoptsclient_requirements.txt

The utils file imports pyudev, however this library is not listen in the client requirement file.
Fixes Issue #1443

requirements: client: Add missing pyudev library

---

tools/cron/github_cron.py

Fixes a use case when someone appended a newline character to the magic tag command.

cron: magic_tag: Strip comment body

---

errata/zephyr.yaml

Since the mentioned Zephyr issue is closed, this test's failure should not be marked as awating an errata anymore.

errata: Remove BASS test from errata list

---

autopts/pybtp/iutctl_common.py

Add | symbol between packet header and data for
BTP command. This could prove useful, as user
can see command data without counting bytes.

log: Add "|" symbol to identify header in raw data

---

autopts/ptsprojects/bluez/btestcase.py
autopts/ptsprojects/bluez/gap.py
autopts/ptsprojects/bluez/iutctl.py
autopts/ptsprojects/bluez/sm.py
autopts/workspaces/bluez/bluez.pqw6

This updates the current BlueZ AutoPTS support:
- Remove/update invalid PIXITs
- Pass path to log file when starting the IUT, to avoid the error below:
2025-03-13 10:26:13,234 LT1-thread root ERROR client.py: 
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
File "/home/iulia/auto-pts/autopts/client.py", line 967, in _run_test_case
test_case.pre_run()
File "/home/iulia/auto-pts/autopts/ptsprojects/testcase.py", line 745, in pre_run
cmd.start()
File "/home/iulia/auto-pts/autopts/ptsprojects/testcase.py", line 267, in start
self.func(*args, **self.kwds)
File "/home/iulia/auto-pts/autopts/ptsprojects/bluez/iutctl.py", line 59, in start
self.socket_srv = BTPSocketSrv()
^^^^^^^^^^^^^^
File "/home/iulia/auto-pts/autopts/pybtp/iutctl_common.py", line …

bluez: Update current support

---

doc/btp_gap.txt

Current description is bogus (likely copy-paste error from Periodic Report event) and makes no sense for PAST received event. Since event content is not currently used by autoPTS we can fix this. Only upstream user (Mynewt) is not following current doc for this event anyway.
While there are couple other parameters that could be added to this event for now lets keep it in line with detail level of Periodic Sync Established event.

doc: Fix Periodic Transfer Received event

---

errata/mynewt.yaml

Add errata for testcase.
This test case fails if we support only one L2CAP channel. Specification states "one or more".

mynewt/errata: Add GATT test errata

---

autopts/wid/sm.py

The global variable `SM_ACL_DISCONN_ROUND` is used to save the current number times of ACL disconnection. The default value of the `SM_ACL_DISCONN_ROUND` should be 0 when the test case is starting.
But when testing more than one case, the initialization value of the variable SM_ACL_DISCONN_ROUND is not 0, because the previous status is not cleared.
Add a global variable `SM_TEST_CASE_NAME` to save the test case name corresponding to the variable `SM_ACL_DISCONN_ROUND`. When the test case name is not same as the current test case name, clear the variable `SM_ACL_DISCONN_ROUND` because it is a new test sequence of new test case.

SM: Update wid 102

---

autopts/ptsprojects/stack/layers/gatt.py
autopts/wid/gatt.py

This WID requires context from previous MMIs and is used to pass size of characteristic value to LT.
It is used in following tests:
GATT/SR/GAW/BI-32-C
GATT/SR/GAW/BI-33-C
GATT/SR/GAW/BI-39-C
GATT/SR/GAW/BI-40-C

wid: Implement GATT WID 154

---

autopts/wid/gap.py

Added wid 246 and 247 to return handle of a characteristic with specified permissions which required by new MMIs.
They're used in following tests:
GAP/SEC/SEM/BV-40-C
GAP/SEC/SEM/BV-22-C

wid: Add missing WID for GAP layer

---

autopts/bot/common.py
autopts/bot/zephyr.py
autopts/ptsprojects/boards/nrf53.py
autopts/ptsprojects/boards/nrf53_appcore.py
autopts/ptsprojects/boards/nrf53_audio.py
autopts/ptsprojects/boards/nrf54h.py
autopts/ptsprojects/boards/nrf5x.py

Add the `build_env_cmd` option to allow configuring a shell command that activates the environment before running `west build` or `west flash`.
This can be used, for example, to activate a Python virtual environment:
source ~/zephyrproject/.venv/bin/activate

bot: zephyr: Add build_env_cmd option

---

cliparser.py

Information about repeat_until_fail param is now displayed when using --help
This is enhancement of https://github.com/auto-pts/auto-pts/pull/1187
Fixes #1491

bot: add info about repeat_until_fail param

---

autopts/ptsprojects/zephyr/cap.py

The test case was failing due to missing advertisement setup for the IUT in Non-Bondable mode. 
This commit adds the required advertisement enablement to support Targeted Announcements (0x01).

Fix: Add missing advertisement enablement for CAP/CL/ADV/BV-02-C

---

autopts/bot/common.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py
autopts/utils.py
tools/cron/common.py
tools/cron/remote_terminal.py

Originally, error.txt was used solely to pass error information from the bot to the cron job, which then posted a comment under the PR. However, since the presence of error.txt now also signals the cron to terminate the bot, even less critical issues like a build or flash failure trigger early termination. As a temporary workaround, let's move the report.make_error_txt call to the end of the bot cleanup phase. A more robust error.txt handling mechanism should be implemented in the future.

common: Move error.txt creation to the end of bot cleanup

---

autopts/bot/common.py
autopts/ptsprojects/zephyr/iutctl.py
autopts/pybtp/iutctl_common.py
cliparser.py

Add support for reading data transmitted over additional UART instance. nrf5340 emulates two/three virtual COM ports one of which outputs logs from network core.
Fixes #1496
Example:

IUT: log data from network core

---

autopts/pybtp/btp/gatt.py

Add gatt_command_rsp_succ() to eatt_conn BTP command - the command response handling was missing. When another command was being called after eatt_conn, BTP ERROR occured because response from the former command was still on rx queue and was interpreted as response to the latter BTP command

btp: gatt: fix eatt_conn btp command

---

autopts/ptsprojects/zephyr/gap.py

This PIXIT was removed while upgrading to PTS 8.9.1. 
However, only PIXIT name was changed; the option is still there.

zephyr: Add timeout PIXIT in GAP layer

---

autopts/ptsprojects/mynewt/l2cap.py

For PTS 8.10 PIXIT fields were removed,
but functions using those fields were present.
Remove functions that apply missing PIXITs.

mynewt: Remove non-existent PIXIT functions

---

autopts/ptsprojects/zephyr/iutctl.py
autopts/pybtp/iutctl_common.py
tools/merge_db.py

Add missing log file closing.
Replace `pass` with `continue` in the catch clause serial.SerialException, because the variable `data` could be unassigned or contain old logs.

common: Fix LoggerWorker closing

---

autopts/ptsprojects/zephyr/hap.py
autopts/ptsprojects/zephyr/tmap.py

Modify 2 occurences of TSPX_TARGET_LATENCY to be
TARGET_BALANCED_LATENCY_RELIABILITY which is the value that the Zephyr BAP Unicast client uses.

Zephyr: Make TSPX_TARGET_LATENCY consistent

---

autopts/bot/zephyr.py
cliparser.py

If project_path is provided, assume that zephyr.exe is normally located under tests/bluetooth/tester/build/zephyr/. The kernel_image option is still kept, as it can be used to point to a custom location.

cliparser: zephyr: Allow skipping kernel_image when --nb is used

---

autopts/config.py
autopts/ptsprojects/iutctl.py
autopts/ptsprojects/zephyr/iutctl.py

The --flash option is optional and it does not exist in every build. By default, flash.bin is generated in the work directory. Let's remove it after each test case to avoid fails caused by changes in settings.

iutctl: zaphyr: native: Remove flash.bin after each test case

---

autopts/bot/common.py
autopts/client.py
autopts/ptsprojects/iutctl.py
autopts/ptsprojects/utils/btattach.py
autopts/pybtp/iutctl_common.py
cliparser.py

There is no need to run btattach at every test case. By default, unless btattach_at_every_test_case is specified, btattach is run only once, during IUT initialization.

iutctl: btattach: Add option btattach_at_every_test_case

---

autopts/client.py
cliparser.py

If logging started before autoptsclient_zephyr_65001.log was initialized, subsequent logs were missing. Initialize the log file as early as possible to avoid this.

client: cliparser: Fix simple client logging

---

cliparser.py

AutoPTS does not support running IUT in QEMU or native mode on Windows. Previously, attempts to do so resulted in unclear exceptions. Now the parser exits earlier with a clear warning.

cliparser: Prevent running QEMU or native mode under Windows

---

cliparser.py

If hci was set to 0, it was treated as false.

cliparser: Fix check args.hci against None instead of truthiness

---

autopts/wid/gap.py

GAP/PADV/PASE/BV-04-C
GAP/PADV/PASE/BV-06-C
Sync is already established in previous steps following previous WIDs, adding test cases in the exception list to not start sync again.

zephyr: add test cases to exceptioned list for creating sync

---

autopts/ptsprojects/iutctl.py

Use finally keyword instead of except to ignore any errors. If we only handle BTPError exception, in any other case the remaining commands in  _stop_native_mode won't be executed.

iutctl: fix stop native mode
