auto-pts/auto-pts

test/stylecheck.py

This script will be used to test for coding style regressions in PRs

new script to check coding style

---

ptsprojects/zephyr/gatt.py

Patch update GATT test cases attributes for verification with current
Zephyr OS predefined attributes.

zephyr: gatt: Update gatt attribute database

---

ptsprojects/zephyr/mesh_wid.py

Patch fixes regular expressions of raw strings for mesh wids.

mesh_wid: Fix regular expression formulas of raw strings

---

autoptsclient-bluez.py

This patch updates and fixes autoptsclient-bluez.py to support bluez.

bluez: Update to support bluez

---

bot/config.py.sample
bot/zephyr.py

This patch set adds support in BOT for
- Support reel_board
- Local IP address
- Multiple IP addresses for mesh

Update bot to support reel board

---

bot/common.py
bot/config.py.sample
bot/zephyr.py

This PR updates the config to support different options and environment.

bot: update config

---

bot/common.py
bot/zephyr.py
ptsprojects/zephyr/__init__.py

Added a few more information to email body and refactor the mail composing routine.

bot: Refactor email composing

---

bot/config.py.sample
ptsprojects/zephyr/gap.py
ptsprojects/zephyr/gap_wid.py
ptsprojects/zephyr/gatt.py
ptsprojects/zephyr/gatt_wid.py

Fix GAP/BROB/BCST/BV-03-C test case:
Disabled advertising in test case. Removed repeated
definition of pixit parameter.
Update Update GATT/CL/GAC/BV-01-C test case 
Update test case to use gatt_wid handlers.

gap/gatt: Test cases (GAP/BROB/BCST/BV-03-C/GATT/CL/GAC/BV-01-C ) fix and update.

---

bot/zephyr.py
ptsprojects/stack.py
ptsprojects/zephyr/gap.py
ptsprojects/zephyr/gap_wid.py
ptsprojects/zephyr/gatt_wid.py
pybtp/btp.py

Patchset apart of this hotfix contains fix for GAP/BOND/BON/BV-04-C, rework of GAP/CONN/UCON/BV-06-C (still not PASS due to PTS issue), and code move from gatt_wid.py to stack.py.

Hotfix not sending regressions list

---

bot/common.py
bot/zephyr.py

Small changes to add result.txt and attach result files to email.
Fixes: #298, #299, #300

bot: small changes for email and result

---

README.md
autoptsclient_common.py
autoptsserver.py
autoptsserver_requirements.txt
bot/zephyr.py
ptscontrol.py
ptsprojects/zephyr/gatt_wid.py
pybtp/parser.py
winutils.py

This fixes issue we had using Interop.PTSControl.dll,
this dependency has been removed.
With this PTS COM is used directly via Dispatch based COM object.
The IronPython dependency has been removed so that run this
script with Python 3.

ptscontrol: Refactor server side to use PTS COM interface

---

ptsprojects/zephyr/gap.py
pybtp/btp.py

Related to:
3f7f830 btp: Clean up UUID conversion related code

btp: Update omitted UUID conversion related code

---

autoptsclient_common.py
ptscontrol.py
ptsprojects/stack.py
ptsprojects/zephyr/mesh.py
ptsprojects/zephyr/mesh_wid.py

Relates to: https://github.com/zephyrproject-rtos/zephyr/pull/16601

Fix test case related to SAR timeout

---

README.md
autoptsclient_common.py
autoptsclient_requirements.txt

Make results of test cases stand out a bit more
with font color matching the given result.

Add coloring to test result logs

---

ptsprojects/zephyr/mesh.py
ptsprojects/zephyr/mesh_wid.py

Mesh fixes

---

doc/btp_spec.txt

These are the proposed changes and additions to the BTP specification. Some of these changes can be useful for autopts testing and others for general Bluetooth test automation

[RFC] BTP API changes

---

doc/btp_spec.txt

I'll  update btp_spec as I go through the tests

doc/btp_spec: document advertisement / scan response data format

---

ptsprojects/zephyr/sm.py

Fix zephyr SM/MAS/PKE/BV-01-C testcase

---

autoptsclient-mynewt.py

This reverts commit fca59171718ca1e5792b09c218007edd1f366d08.

Revert "mynewt: Remove mention of Zephyr from client"

---

bot/mynewt.py

Introduced by ae6d33123366c5b60632c2673f0e9f9cd8ae0ccf.

mynewt: Fix a regression with removed kernel argument

---

ptsprojects/zephyr/sm.py

This PR adds tests mentioned in https://github.com/intel/auto-pts/issues/394.

Zephyr: added Secure Connections tests

---

workspaces/Mynewt Nimble Host/Mynewt Nimble Host.pqw6
workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Workspaces for Mynewt and Zephyr master were updated to PTS 7.6.2

PTS 7.6.2 - workspaces update

---

ptsprojects/mynewt/mesh.py
ptsprojects/zephyr/mesh.py

Second pts instance hasn't got updated pixit param.

mesh.py: update_pixit_param for 2nd pts

---

autoptsclient-zephyr.py
autoptsclient_common.py
ptsprojects/testcase.py
ptsprojects/zephyr/iutctl.py
ptsprojects/zephyr/ztestcase.py
pybtp/iutctl_common.py

Collects logs from device for each test case automatically and puts
it in separate folder for easy access.

common: Use rtt2pty to automatically collect logs from device

---

ptsprojects/zephyr/gatt_wid.py

This PR fixes https://github.com/intel/auto-pts/issues/360 and https://github.com/intel/auto-pts/issues/366

Zephyr gatt wids

---

bot/config.py.zephyr.sample
ptsprojects/stack.py
ptsprojects/zephyr/gap.py
ptsprojects/zephyr/gatt.py
ptsprojects/zephyr/gatt_wid.py
ptsprojects/zephyr/l2cap.py
ptsprojects/zephyr/sm.py
ptsprojects/zephyr/sm_wid.py
wid/l2cap.py
workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Created a separate commit per layer. 
Zephyr PR: zephyrproject-rtos/zephyr/pull/29572

Add/Fix tests required for NCS 1.4 qualification

---

autoptsclient-mynewt.py
ptsprojects/mynewt/iutctl.py
ptsprojects/mynewt/ztestcase.py

Adds support for automatic log collecting for Mynewt via RTT, using
feature added in https://github.com/intel/auto-pts/pull/405

mynewt: Use rtt2pty to automatically collect logs from device

---

wid/mesh.py

Fix a couple of issues omitted when migrating to Python 3 and add a new WID implementation.

wid: Minor updates and fixes

---

wid/mmdl.py

https://github.com/zephyrproject-rtos/zephyr/pull/32369 fixes problems
that sleeping was a workaround for.

wid: Remove unnecessary sleep calls

---

ptsprojects/mynewt/mesh.py
workspaces/Mynewt Nimble Host/Mynewt Nimble Host.pqw6
workspaces/Mynewt Nimble Host/Mynewt Nimble Host.pts

Updated ICS with supported and mandatory erratum, added new MESH test, which is passing

Mynewt: update for PTS v8.0.3

---

ptsprojects/zephyr/iutctl.py

Fixes: https://github.com/intel/auto-pts/issues/463
Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

zephyr: Fix TypeError concatenate

---

bot/zephyr.py

Use '-DOVERLAY_CONFIG' option to specify custom settings that will be
merged with the default config. No need for copying and editing the
default configuration anymore.
'-DCONF_FILE' and '-DOVERLAY_CONFIG' seem to do the same thing now and
using a copy of the default config with those options is broken so this
is a workaround for that issue.

zephyr: Workaround for issue with custom config file

---

autoptsclient-bluez.py
autoptsclient-mynewt.py
autoptsclient-zephyr.py
autoptsclient_common.py

Quite a few parts of code of clients could be unified, what will make
it easier to add new run options that are common to all clients.

common: Unify common parts of autopts clients

---

README.md
autoptsclient-zephyr.py
autoptsclient_common.py
ptsprojects/zephyr/iutctl.py

Signed-off-by: Lingao Meng <menglingao@xiaomi.com>

native: add support test on native posix mode

---

bot/config.py.zephyr.sample

Some Security Manager tests were renamed.

bot: Update tests name for PTS 8.0.3

---

ptsprojects/stack.py
pybtp/btp.py
wid/mmdl.py

- Remaining Time should not be `None`
- Add missing WID

common: Fix MMDL test cases

---

bot/zephyr.py

No need to source this file since we are using west now.

bot/zephyr: Do not call 'source zephyr-env.sh'

---

pybtp/btp.py

Looks like copy-and-paste error.

common: Remove duplicated gattc_read_multiple_rsp

---

ptsprojects/zephyr/mesh.py

This value will be used in future PTS releases during provisioning.

zephyr: Update Static OOB PIXIT value

---

bot/config.py.zephyr.sample

This makes it easier to compare overlays. Also removed duplicated entry.

bot: Cleanup zephyr sample config

---

bot/mynewt.py
bot/zephyr.py

Fallback to default value if optional configuration is not provided.

bot: Fix optional configuration arguments

---

bot/common.py

bot: Make report.txt a bit more readable

---

autoptsclient-bluez.py
autoptsclient-mynewt.py
autoptsclient-zephyr.py
autoptsclient_common.py
bot/mynewt.py
bot/zephyr.py
ptsprojects/bluez/gap.py
ptsprojects/bluez/sm.py
ptsprojects/mynewt/gap.py
ptsprojects/mynewt/gatt.py
ptsprojects/mynewt/l2cap.py
ptsprojects/mynewt/mesh.py
ptsprojects/mynewt/sm.py
ptsprojects/zephyr/dis.py
ptsprojects/zephyr/gap.py
ptsprojects/zephyr/gatt.py
ptsprojects/zephyr/l2cap.py
ptsprojects/zephyr/mesh.py
ptsprojects/zephyr/mmdl.py
ptsprojects/zephyr/sm.py

and add re-setting them up after recovery.

common: Unify the pixits setting

---

autoptsclient-zephyr.py
autoptsclient_common.py
ptsprojects/zephyr/iutctl.py

as in this mode it is not needed.

zephyr: Make kernel_image arg optional in HW mode

---

bot/common.py
errata.yaml

If test case awaits PTS errata, its name can be listed together with case
number in errata.yaml file, so that an appropriate note can be added to
the reports.

bot: Add errata.yaml

---

errata.yaml

Also, convert file from Windows to Unix format.

errata: Add erratas for GAP/SEC/AUT/BV-14-C and GAP/SEC/AUT/BV-23-C

---

tools/ics_rst_from_html.py

The tool parses html file, saved form page https://launchstudio.bluetooth.com/ICS/<some-id>, that contains ICS tables, into rst file.

tools: Add ICS html-to-rst file parser

---

autoptsclient_common.py
bot/common.py

If test case had more attempts before PASS, saves the attempt number
in reports.

bot: Add to reports attempt number of PASS

---

README.md
autoptsclient-bluez.py
autoptsclient-mynewt.py
autoptsclient-zephyr.py
autoptsclient_bot.py
autoptsclient_common.py
autoptsserver.py
bot/common.py
bot/config.py.mynewt.sample
bot/config.py.nrf.sample
bot/config.py.zephyr.sample
bot/mynewt.py
bot/zephyr.py
ptscontrol.py
ptsprojects/bluez/iutctl.py
ptsprojects/mynewt/iutctl.py
ptsprojects/stack.py
ptsprojects/testcase_db.py
ptsprojects/zephyr/iutctl.py

Bot client classes extends simple client class, so console input args now enabled for bot and they can override config.py settings.

bot: common: Unify bot clients

---

ptsprojects/mynewt/sm.py

Fixed wrong conditions according to TS

mynewt/sm: fixed test cases' conditions

---

ptsprojects/zephyr/gatt.py
wid/gatt.py

Those tests require performing ATT Read and not Read Blob.

zephyr: Fix GATT/CL/GAR/BI-0{1-5} tests

---

ptsprojects/mynewt/gatt.py
ptsprojects/mynewt/gattc_wid.py

Fixed tests having issues with read/read long

Mynewt: fix GATT/CL tests

---

ptsprojects/stack.py
wid/l2cap.py

We are interested only in channel 0 for this wid.

wid: Fix handling of wid 261

---

autoptsclient_bot.py
autoptsclient_common.py

to allow exit handling by bot or Linux terminating.

client: Propagate SIGINT to upper layers

---

workspaces/Mynewt Nimble Host/Mynewt Nimble Host.pqw6

Updated workspace using old ICS file - as there's no new TCRL.

Mynewt: update workspace to PTS 8.1.1

---

autoptsserver.py
bot/common.py
bot/mynewt.py
bot/zephyr.py

Replaces hardcorded VirtualBox name in report email.

Add detection of platform on which autoptsserver is running.

---

workspaces/zephyr/zephyr-master/zephyr-master.pqw6
workspaces/zephyr/zephyr-master/zephyr-master.pts

Enabled Provisioner Role with Adv bearer and mandatory features
required by it, Configuration Client Model, Health Client Model and
Multiple Subnet Support.

Zephyr: enable MESH supported features

---

wid/gap.py

This was affecting GAP/CONN/DCEP/BV-05-C and GAP/CONN/DCEP/BV-06-C.

wid: Add support for GAP WID 403

---

bot/common.py
bot/mynewt.py
bot/zephyr.py

When preparing a report the bot should add information about current
commit from all configured repositories. All repositories in 'git'
config section will be displayed in status information.
Add option to do `west update` on a repo.

bot: Display sha from multiple repositories and add option to do `west update`

---

ptsprojects/boards/dialog_da1469x_dk_pro.py

check_call was moved in between merging two PRs.

dialog: Fix import

---

ptsprojects/mynewt/gap.py
ptsprojects/mynewt/gatt_wid.py
ptsprojects/mynewt/l2cap.py
wid/gap.py

This PR contain various fixes for Nimble host for PTS 8.1.2

Nimble host fixes

---

pybtp/types.py
wid/__init__.py
wid/dis.py
wid/gap.py
wid/gatt.py
wid/l2cap.py
wid/mesh.py
wid/mmdl.py
wid/sm.py

- Define a aggregate structure for wid parameters to make extending easier
in the future.
- Fix whitespace issues
- Fix typos and other warnings in the entire wid/ directory

wid: Refactor WID handlers

---

bot/zephyr.py
ptsprojects/boards/__init__.py
ptsprojects/boards/nrf53.py
ptsprojects/boards/nrf5x.py

Previously, only nrf52 was supported.

boards: Add support for nrf53

---

bot/common.py
bot/mynewt.py
bot/zephyr.py

Now every test with PASS verdict has appropriate entry in report.xlsx
with matching filename of XML file from PTS. All XML files are also
added to seperate "XMLs" folder uploaded to drive.

Include XML files with test execution logs from PTS side in report

---

bot/common.py

Under Windows bot skipped the folder creation.

bot: Fix creating XMLs folder

---

README.md
autoptsclient_common.py
autoptsserver.py
bot/common.py
bot/config.py.zephyr.sample
bot/mynewt.py
bot/zephyr.py
ptscontrol.py
tools/cron/__init__.py
tools/cron/autopts_bisect.py
tools/cron/autopts_cron.py
tools/cron/common.py
tools/cron/config_zephyr_bisect.py.sample
tools/cron/cron_config.py.sample

Allows to schedule cyclical jobs or trigger them with magic sentence in Pull Request comment.

tools: Add autopts-cron.py tool

---

pybtp/btp/gap.py
wid/gap.py

Dialog board sends 0 after reset. Added fix to discard this zero.

Mynewt test fixes

---

utils.py

Missing after client parser refactor.

ykush: Add waiting for end of subprocess

---

doc/btp_spec.txt
pybtp/btp/gap.py

Switched order of parameters for clarity.
@sjanc

apps/bttester/set_filter_accept_list: fix doc

---

tools/cron/common.py
tools/cron/cron_config.py.sample

Basic setup allowing to run tests and collect results, without log
upload.

Cron: add minimal setup for NimBLE

---

autopts/ptsprojects/zephyr/gap.py

zephyr: Fix GAP/SEC/SEM/BV-58-C test

---

autopts/ptsprojects/zephyr/gap.py

zephyr: Fix GAP/SEC/SEM/BV-61-C

---

autopts/bot/mynewt.py

when rtt_log option is enabled.

mynewt: Apply overlays for RTT logs automatically

---

autopts/wid/mesh.py

This is required by MESH/PVNR/PBADV/BV-01-C.

MESH: add hdl_wid_56

---

autopts/bot/common.py
autopts/bot/config.py.mynewt.sample
autopts/bot/config.py.zephyr.sample
autopts/bot/mynewt.py
autopts/bot/zephyr.py
autopts/ptsprojects/boards/__init__.py
autopts/ptsprojects/boards/nrf52.py
autopts/ptsprojects/boards/nrf52_wsl.py
autopts/ptsprojects/boards/nrf5x.py
autopts/ptsprojects/boards/reel_board.py
autopts/ptsprojects/mynewt/iutctl.py
autopts/ptsprojects/mynewt/post_tc.py
autopts/ptsprojects/zephyr/iutctl.py
autopts/ptsprojects/zephyr/post_tc.py
tools/cron/autopts_cron.py
tools/cron/common.py
tools/cron/cron_config.py.sample

since Zephyr SDK >=0.14.0 supports building under Windows.

zephyr: Make building with WSL optional

---

autopts/bot/iut_config/zephyr.py

zephyr: Add tests to overlay privacy.conf

---

autopts/bot/iut_config/mynewt.py
autopts/ptsprojects/mynewt/gap.py
autopts/ptsprojects/stack.py
autopts/pybtp/btp/gap.py
autopts/wid/gap.py
errata.yaml

give some time to finish pairing before disconnecting, to save the keys.

mynewt: wait for pairing in GAP/BOND/BON/BV-01-C

---

autopts/workspaces/Mynewt Nimble Host/Mynewt Nimble Host.pqw6

Some ICS where introduced and some IXITs changed dafault values.

mynewt: update workspace to PTS v8.3

---

autopts/bot/iut_config/zephyr.py
autopts/wid/gap.py

Some changes to the config and wids were needed.

Fix GAP/CONN/ACEP/BV-01-C and GAP/CONN/DCEP/BV-01-C

---

autopts/ptsprojects/mynewt/gatt_wid.py
autopts/wid/gatt.py

In some cases PTS requires Reliable Write and in other Write Long.

wid: Fix GATT Reliable Write tests

---

tools/cron/common.py

In case of running multiple jobs one after another, if one of them failed, but no exception was thrown, then no logs with backtrace were left.

cron: Save old logs for a week

---

autopts/client.py

and simplify run_test_case as part of the code is no longer affected by 'while'.

client.py: Init the logging handler later

---

README.md

Signed-off-by: supperthomas <78900636@qq.com>

Zephyr: fix the link of guide

---

autopts/ptsprojects/boards/nxp_rt1060.py

i have test the pts with rt1060 using auto-pts in NXP, I want contribution to it and this Code that conforms to company specifications ， we are using the Open SDK I.M RT1060 If you are interested you can get the code for the board side here https://mcuxpresso.nxp.com/en/welcome

Implement Zephyr PTS test  application with nxp rt1060

---

doc/overview.txt

This helps to quickly get overview of defined services.

doc: Add summary of defined BTP services

---

autopts/ptsprojects/boards/nrf53_audio.py

boards: nrf53_audio: Flash NETCORE with Zephyr controller

---

autopts/wid/gap.py

Make sure we configure proper address type for advertising if IUT is validating it.

wid: Explicitly request RPA in WID 80

---

autopts/pybtp/btp/mesh.py
autopts/wid/mesh.py
doc/btp_mesh_node.txt

added missing net_hey_idx parameter to netkey_get

Fix mesh btp mesh_cfg_netkey_get cmd

---

autopts/bot/iut_config/zephyr.py
autopts/ptsprojects/stack.py
autopts/wid/gap.py

Use RPA if privacy is enabled.

wid: Use proper advertising address type in GAP WID 20001

---

autopts/ptsprojects/zephyr/gap_wid.py

This fixes GAP/IDLE/NAMP/BV-01-C with PTS 8.4.

zephyr: Use common GAP WID 73 handler

---

autopts/wid/aics.py

This PR adds hdl_wid_11 in aics.py for setting gain mode.

Add wid  in aics.py

---

autopts/bot/common.py
autopts/bot/iut_config/zephyr.py
autopts/client.py

Reduce the number of reads of the supported test case list from the workspace.

bot: common: Cleanup test case list generation

---

autopts/wid/sm.py

This is used by PTS 8.4.1 and was affecting SM/CEN/EKS/BV-01-C

wid: Add support for SM WID 174

---

autopts/bot/iut_config/mynewt.py
autopts/ptsprojects/mynewt/gap.py
autopts/ptsprojects/mynewt/gap_wid.py
autopts/ptsprojects/stack.py
autopts/wid/gap.py

Added tests to respective overlays.
Accomodated some wids to use GATT Client service, when enabled. Added setting in GAP stack to set if User Interaction is available in pairing.

Mynewt: fixes for GAP/SEC/SEM

---

autopts/client.py
autopts/ptscontrol.py
autopts/winutils.py
autoptsserver.py

autoptsserver: Refactor stopping PTS and dongle selection

---

autopts/workspaces/nimble-master/nimble-master.pqw6

Also removes filepath from workspace file.

Mynewt: update workspace to PTS 8.5

---

autopts/ptsprojects/mynewt/gatt.py
autopts/pybtp/btp/btp.py

Add command for registering GATT Client service and call it for GATT/CL tests.

mynewt: register GATT Client

---

autopts/pybtp/btp/btp.py

Reducing amount of boilerplate code - event handler functions

pybtp: btp: event handler

---

autopts/ptsprojects/zephyr/bap.py
autopts/wid/bap.py
autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Add wids used in BAP/USR test cases for unicast server.

zephyr: bap: Add support for BAP/USR tests

---

autopts/ptsprojects/mynewt/gap.py
autopts/ptsprojects/mynewt/gap_wid.py
autopts/wid/gap.py

Adjusted WIDs and test procedure to GATT Client.

Mynewt: fix GAP/SEC/SEM tests

---

tools/cron/autopts_bisect.py

send_email function has been moved recently into other location.

cron: Fix broken bisect import

---

tools/list_testcases.py

A tool for printing all test cases from workspace.

tools: Add list_testcases.py

---

autopts/ptsprojects/stack.py
autopts/pybtp/btp/mesh.py
autopts/wid/mesh.py
doc/btp_mesh_node.txt

Updating wid 500 and 7 according to latest PTS updates.
tester PR: https://github.com/zephyrproject-rtos/zephyr/pull/63872

Mesh pts fixes for updated wids

---

autopts/wid/gap.py

This was affecting GAP/CONN/CPUP/BV-02-C.

wid: Add GAP WID 210 implementation

---

autopts/client.py
autopts/ptscontrol.py
autoptsserver.py

Fix a few oversights in xmlrpc refactor:
- The server superguard did not update its start time, so it kept resseting the xmlrpc.
- The exception handler of init_pts set the global end flag, which skipped recovery.
- If PTSLogger got an exception before setting a result, the autopts server hung forever.

common: Fix recovery

---

autopts/client.py

Bot argument was missin in a client.

bot: client: Fix missing server_count argument

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

zephyr: Update workspace to latest changes in Launch Studio project

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Disable MCP depentency on MCS (only GMCS is supported).

zephyr: Update workspace

---

autopts/pybtp/btp/mcp.py
autopts/wid/mcp.py
doc/btp_mcp.txt

Expanding MCP Discovery Event with MCS and OTS characteristic handles.

zephyr: tester: MCP Discovery Event

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

Removed features not supported by Zephyr.

zephyr: Update PTS workspace

---

errata/zephyr.yaml

Adding GMCS and MCP issues related to specific test cases.

errata: GMCS and MCP test case issues

---

autopts/ptsprojects/zephyr/iutctl.py

The RTT logs have not been enabled if the --gdb option was used.

zephyr: Allow RTT logs even while debugging

---

errata/zephyr.yaml

Removed few testcases with resolved issues, adding new issue

errata: GMCS testcase issues

---

autopts/client.py
autopts/ptsprojects/zephyr/gatt.py
autopts/wid/gatt.py

Replace BTP lock with SynchPoint.

zephyr: Fix GATT/SR/GAN/BV-02-C

---

autopts/ptsprojects/stack.py
autopts/wid/gmcs.py
errata/zephyr.yaml

Update handlers for GMCS server tests.
Updating list of issues.

zephyr: gmcs: GMCS tests

---

autoptsclient_requirements.txt
autoptsserver_requirements.txt

The tested working version is yepkit-pykush-0.3.5.

README: Add info how to install yepkit-pykush module

---

autopts/pybtp/btp/__init__.py
autopts/pybtp/btp/btp.py
doc/overview.txt
tools/generate_profile.py

Some important imports were missing.

tools: generator: Add missing imports

---

errata/zephyr.yaml

Some issues have been resolved.

zephyr: errata: Remove notes from fixed test cases

---

autopts/rtt.py

PTY creation may fail for different reasons and the log speeds up finding the problem.
@piotrnarajowski

rtt: btmon: Print stderr message in case of error

---

autopts/client.py
autopts/ptscontrol.py

Using the the logging._lock was a mistake, because it is used internally for handlers management, not to protect a file handler while logging. Log file handlers have their own locks. Instead of trying to get to internal locks, we can create our own and just monky patch the Logger._log method to make use of it globally.

client: LTThread: Use other lock to protect logger

---

autopts/bot/iut_config/zephyr.py
autopts/ptsprojects/stack/layers/__init__.py
autopts/ptsprojects/stack/layers/gtbs.py
autopts/ptsprojects/stack/stack.py
autopts/ptsprojects/zephyr/__init__.py
autopts/ptsprojects/zephyr/gtbs.py
autopts/pybtp/btp/tbs.py
autopts/wid/__init__.py
autopts/wid/gtbs.py
autopts/wid/tbs.py
doc/btp_gtbs.txt
doc/btp_tbs.txt

This commit implements GTBS server tests using TBS btp.
Merge after https://github.com/auto-pts/auto-pts/pull/1104

zephyr: tester: GTBS server tests

---

autopts/bot/iut_config/zephyr.py
autopts/ptsprojects/stack/layers/ots.py
autopts/ptsprojects/stack/stack.py
autopts/ptsprojects/zephyr/__init__.py
autopts/ptsprojects/zephyr/ots.py
autopts/ptsprojects/zephyr/ots_wid.py
autopts/pybtp/btp/__init__.py
autopts/pybtp/btp/btp.py
autopts/pybtp/btp/ots.py
autopts/wid/__init__.py
autopts/wid/ots.py
errata/zephyr.yaml

Add support for OTS server tests

zephyr: tester: OTS tests

---

autopts/ptsprojects/boards/nrf54l.py

boards: add nRF54L15 device

---

autopts/ptsprojects/boards/board_ext.py

The goal of this board is to allow an external program to manage the building/flashing and getting the resetting command.

Add a new `board_ext` board

---

autopts/ptsprojects/zephyr/hap.py
autopts/pybtp/btp/hap.py
autopts/wid/hap.py

Fix wid that handles connection to PTS, add missing wid handlers, fix hauc discovery data parsing
Fixes HAP/HAUC/DISC/BV-01-C, HAP/HAUC/SGGIT/SER/BV-01-C, HAP/IAC/CGGIT/CHA/BV-01-C

zephyr: tester: Fix HAP wid handlers

---

autopts/wid/micp.py

Fix characteristic UUID from MMI that changed after PTS update. Fixes MICP/CL/CGGIT/CHA/BV-01-C

zephyr: micp: fix MICP wid

---

autopts/bot/iut_config/mynewt.py
autopts/ptsprojects/mynewt/__init__.py
autopts/ptsprojects/mynewt/bap.py
autopts/ptsprojects/mynewt/bap_wid.py
autopts/workspaces/nimble-master_leaudio/nimble-master_leaudio.pqw6

Add broadcast test support for mynewt-nimble.

Broadcast tests

---

autopts/ptsprojects/mynewt/pacs.py
autopts/ptsprojects/mynewt/pacs_wid.py
autopts/workspaces/nimble-master_leaudio/nimble-master_leaudio.pqw6

Adds support for testing PACS with mynewt-nimble.

Add test environment for PACS in mynewt-nimble.

---

.github/workflows/check_pr_changes.yaml

This commit adds a new workflow file. The purpose is to trigger test run of specific layer if PR contains changes made in autopts/wid/ directory.
Related to https://github.com/auto-pts/auto-pts/issues/953, https://github.com/auto-pts/auto-pts/issues/1135

CI: add workflow file for automated test run on PR

---

autopts/ptsprojects/zephyr/dfu.py
autopts/ptsprojects/zephyr/mbt.py

This allows to run those without MMDL.

zephyr: Enable MESH DFU and MBT

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This syncs workspace with Zephyr's Launchstudio project.

zephyr: Update PTS workspace with latest OTS changes

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This is required dependendy for MCP.

zephyr: Enable support for Object Changed Characteristic (4/20) in OTS

---

autopts/wid/cap.py

I've added these tests for our stack. The ptsproject/cap.py is currently here:
https://github.com/bluekitchen/auto-pts/blob/develop-le-audio-broadcast/autopts/ptsprojects/btstack/cap.py

Add CAP Broadcast Assistant tests

---

.github/workflows/check_pr_changes.yaml

This commit changes pull_request event to pull_request_target event. This gives an access to a read/write token as well as secrets enabling github actions bot to comment on pull request to trigger cron.

actions: check_pr_changes: Change pull_request event

---

autopts/bot/mynewt.py

This patch adds progresses to mynewt email report.

mynewt: bot: add progresses to mail report

---

errata/mynewt.yaml

Adding test cases to mynewt errata list

mynewt: errata: add test cases to errata list

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This includes update to TCRL 2024-1.

zephyr: Update PTS workspace to 8.6

---

autopts/bot/common.py
autopts/bot/common_features/report.py
autopts/bot/mynewt.py
autopts/bot/zephyr.py
autopts/client.py
autopts/config.py
autopts/utils.py
autopts/workspaces/nimble-master/nimble-master.pqw6
autoptsserver.py
cliparser.py
test/unittests.py
tools/active_hub_server.py
tools/cron/common.py

If the 'use_backup' option is set to True in a config.py, the bot collects a backup of the stats, so in case of unexpected termination the bot can continue the test series from the test case where it was interrupted.

bot: Add a test run backup mode

---

autopts/wid/bap.py

New TCRL added more tests for CIS connnection in QoS Configured state.

wid/bap: Add more configurations to ac_configs

---

errata/mynewt.yaml

Add L2CAP test case to mynewt errata list

mynewt: errata: l2cap test case

---

autoptsclient_requirements.txt
autoptsserver_requirements.txt

Add missing module to client and server requirements.txt

requirements: add missing module

---

tools/cron/autopts_cron.py

cron: Add --test-case-limit alias to --test_case_limit option

---

errata/mynewt.yaml

Remove stale ones, add new test case.

mynewt: errata: Update errata list

---

tools/cron/autopts_cron.py

If cron setup is Linux + Windows VM, then the autopts repo on the virtual machine should be rebased on PR branch as well.

 cron: pr job: Rebase remote autopts server to PR branch

---

autopts/bot/common.py

This commit implements project name field into report email body.

bot: report: add project name

---

autopts/ptsprojects/boards/nrf54h.py

boards: add nRF54H20 device

---

autopts/pybtp/btp/bap.py
autopts/pybtp/btp/cap.py
tools/generate_profile.py

Bug fixes from https://github.com/auto-pts/auto-pts/pull/1201

Fix cap bap tools

---

autopts/pybtp/btp/vcp.py

btp/vcp: allow set volume with 0..255

---

README.md

Remove old Slack channel link and add IUT specific links.

Update community links

---

autopts/bot/common_features/report.py

For completeness, pull the autoptsserver_65000.log file into tmp folder.

bot: logs: Pull the autoptsserver log file from vm

---

tools/cron/common.py

Add failed/passed tests count to comment with test results

tools: cron: improve pr comment test report

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This is based on test plan for TCRL 2024-2.

zephyr: Update workspace to PTS 8.7.2

---

errata/mynewt.yaml

Add testcase to mynewt errata list

mynewt: errata: add test case

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This enabled PAST related tests in BAP.

zephyr: Update PTS workspace to match latest Qualification Studio files

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

This also updates profiles version to latest versions supported by Zephyr Host.

zephyr: Update workspace to PTS 8.7.4

---

autopts/client.py
autopts/ptscontrol.py
cliparser.py

PTS v8.7.4 introduces "Indecisive" test verdict.

pts: add Indecisive test verdict

---

autopts/wid/mcp.py

Fixes missing wid error for MCP/SR/SP/BV-01-C

wid: add missing MCP wid

---

autopts/client.py

It seems that the 'code' field is specific for the SystemExit class, because while handling other exception I've got this one:
File "/home/codecoup/autopts/client.py", line 1378, in start
if e.code != 0:
AttributeError: 'TimeoutError' object has no attribute 'code'

client: Fix logging an exception at exit

---

autopts/bot/common_features/mail.py

Improves formatting and layout of table in email report

bot: mail: minor improvements

---

doc/btp_gatt.txt

Documentation for this command was missing.

Document Handle Value Multiple Notification

---

autopts/bot/common.py
autopts/bot/common_features/mail.py
autopts/bot/common_features/report.py

Profile_summary function is split to two functions that can return ascii formatted table or html formatted. Html version printed in readme.md was incorrectly formatted by github.

bot: report: adjust profile_summary

---

autopts/bot/iut_config/zephyr.py

Those needs to be build with LE Audio overlay.

bot: zephyr: Add PBP, GMAP and CAS to LE Audio overlay

---

autopts/bot/common.py
autopts/bot/common_features/report.py

Fixes invalid indent of table header

bot: report: fix table indent

---

README.md

The channel name was renamed.
This commit also adds a direct link to the channel.

Update Discord channel name and link in README

---

autopts/ptsprojects/boards/nordic_pca10095.py

If a previous nrf53 build/flash has enabled appprotect, the eraseall command would fail:
subprocess.CalledProcessError: Command 'nrfjprog --eraseall -s xxxxxxxxxx' returned non-zero exit status 16.
ERROR: The operation attempted is unavailable due to readback protection in ERROR: your device. Please use --recover to unlock the device.

boards: nordic_pca10095: Fix recover/erase order

---

autopts/bot/common.py

no_build argument is parsed to disable build and flash in need

bot: Parse no_build argument

---

autopts/ptsprojects/boards/nordic_pca10056.py

If readback protection was enabled at previous image, nrfjprog will handle that and flash the current image without issues.

boards: nordic_pca10056: Use nrfjprog as downloader

---

autopts/workspaces/nimble-master/nimble-master.pqw6
autopts/workspaces/nimble-master/nimble_project_TCRL_2024-2.bqw

TSPC_L2CAP_2_45a (Send Disconnect Request Command - LE (C.22)) was not enabled.

nimble: Update PTS workspace

---

autopts/workspaces/zephyr/zephyr-master/zephyr-master.pqw6

ICS are also updated to TCRL 2025-1.

zephyr: Update workspace to PTS 8.8

---

autopts/wid/l2cap.py

Those are IUT specific so will have to be updated in WID overlays of different behaviour is required.

wid: l2cap: Add implementations for WID 118 274 and 275

---

autopts/bot/iut_config/mynewt.py

bot/nimble: Remove not needed overlay

---

errata/mynewt.yaml

Add GATT test cases that require at least 2 EATT chans to mynewt errata list

mynewt: add test case to errata list

---

autopts/ptsprojects/zephyr/cap.py
autopts/pybtp/btp/cap.py
autopts/wid/cap.py

- Add wid_421
- Add custom test case for CAP/CL/ADV/BV-04-C
- Test requires available contexts to be 0 in both adv and PACS

CAP: Implement CAP/CL/ADV/BV-04-C

---

autopts/wid/gatt_client.py

Adding support for new tests after tcrl update
Fixes GATT/CL/GAS/BV-05-C

mynewt: wid: add support for new GATT/CL test

---

autopts/winutils.py

This change implements Issue #1410

Removing the check for visible windows so to include non-visible as well

---

tools/cron/common.py

If a PR causes the test run startup to fail and no ERROR_TXT_FILE is generated, cron will be restarted indefinitely and block other jobs.

cron: pr_job: Add startup_fail_max_count option

---

autopts/wid/cap.py

Fixes the following tests:
* CAP/CL/ADV/BV-01-C

wid: CAP: Add missing hdl_wid_420

---

autopts/wid/cap.py

wid/cap: Remove trailing whitespace

---

autopts/ptsprojects/mynewt/gap.py

Add dummy value LE supported features to
GAP initialization.

mynewt/gap: Add dummy LE supported features

---

autopts/bot/iut_config/mynewt.py
autopts/wid/gap.py

Add mynewt-specific option for disabling le-audio support.
Add missing wid.

GAP security layer fixes

---

doc/btp_gatt_server.txt

This adds command for explicit database initialization.

doc: Update GATT Server BTP service

---

autopts/rtt.py

Improve general btmon funcionality & stability.

Improve btmon logging via rtt

---

autopts/workspaces/nimble-master/nimble-master.pqw6
autopts/workspaces/nimble-master/nimble_project_TCRL_pkg100.bqw

This includes update to TCRL pkg100.

nimble: Update workspace to PTS 8.10

---

autopts/bot/zephyr.py
autopts/ptsprojects/mynewt/iutctl.py
autopts/ptsprojects/zephyr/iutctl.py
cliparser.py

This option can be used to enable UART hardware flow control.

client: Add rtscts parameter

---

autopts/wid/bap.py

Add missign configurations and properly set PACS locations per test.

wid: Add new tests handling in BAP WID 311

---

autopts/wid/bap.py

BAP/BSNK/STR and BAP/BSRC/STR tests > 35 are new tests with single BIS.

wid: Fix BAP WID 100 handling

---

autopts/utils.py
tools/wid_usage.py

Add custom source log directory option for wid usage script. 
Inform user where the report is generated.

Enhance WID report generation

---

autopts/utils.py
cliparser.py

Introduce --wid_run SERVICE WID argument in CliParser
Add wid_run_tcs() helper to resolve testcases from wid_usage_report.csv
Default wid_usage_report.csv path is BASEDIR/wid_usage_report.csv
Extend args.test_cases with resolved testcases when --wid_run is used
Expose load_wid_report() and get_tc_from_wid() utilities in utils.py for parsing wid_usage_report.csv and mapping (service, wid) -> testcases
**_NOTE -_** This will be fully functional after a complete wid_report.csv file is added.

cli: Add '--wid_run' option to run tcs by service & WID

---

README.md
autopts/bot/common.py
autopts/bot/mynewt.py
autopts/ptsprojects/boards/__init__.py
autopts/ptsprojects/boards/nordic_pca10056.py
autopts/ptsprojects/boards/nordic_pca10095.py

Recover devices to ensure the write protection is disabled
before new image flash.
Fixes "BUILD_OR_FLASH ERROR" observed in https://github.com/apache/mynewt-nimble/pull/2107#issuecomment-3196363035

mynewt: Fix "BUILD_OR_FLASH ERROR" observed on write-protected devices

---

autopts/wid/gmcs.py

This is used in tests that verify Move Relative functinality: GMCS/SR/MCP/BV-12-C
GMCS/SR/MCP/BV-13-C
GMCS/SR/MCP/BV-14-C
GMCS/SR/MCP/BV-75-C

wid: Implement GMCS WID 45

---

errata/zephyr.yaml

This is no longer an issue for those tests.

errata: Remove fixed Zephyr MESH issue
